import { normalizeCareProfileName } from "@/lib/care-profiles/normalize";
import type {
  CareProfileAliasType,
  CareProfileLevel,
  CareProfileMatchConfidence,
  CareProfileReviewStatus,
  DrynessPreference,
} from "@/lib/care-profiles/types";

export type CareProfileAliasFixture = {
  alias: string;
  aliasType: CareProfileAliasType;
  priority?: number;
  allowAmbiguous?: boolean;
};

export type CareProfileFixture = {
  profileKey: string;
  profileLevel: CareProfileLevel;
  displayName: string;
  acceptedScientificName: string | null;
  acceptedCommonName: string;
  taxonRank: string | null;
  wateringIntervalDaysDefault: number;
  wateringIntervalDaysMin: number | null;
  wateringIntervalDaysMax: number | null;
  drynessPreference: DrynessPreference;
  wateringGuidance: string;
  beginnerNote: string;
  matchConfidence: CareProfileMatchConfidence;
  reviewStatus: CareProfileReviewStatus;
  sourceSummary: string;
  aliases: CareProfileAliasFixture[];
};

const sourceSummary =
  "Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.";

function alias(
  value: string,
  aliasType: CareProfileAliasType,
  priority = 50,
  allowAmbiguous = false,
): CareProfileAliasFixture {
  return {
    alias: value,
    aliasType,
    priority,
    allowAmbiguous,
  };
}

function species(
  profileKey: string,
  displayName: string,
  scientificName: string,
  commonName: string,
  wateringIntervalDaysDefault: number,
  range: [number, number],
  drynessPreference: DrynessPreference,
  wateringGuidance: string,
  aliases: CareProfileAliasFixture[],
): CareProfileFixture {
  return {
    profileKey,
    profileLevel: "species",
    displayName,
    acceptedScientificName: scientificName,
    acceptedCommonName: commonName,
    taxonRank: "species",
    wateringIntervalDaysDefault,
    wateringIntervalDaysMin: range[0],
    wateringIntervalDaysMax: range[1],
    drynessPreference,
    wateringGuidance,
    beginnerNote: "Common houseplant starter profile for editable watering setup.",
    matchConfidence: "medium",
    reviewStatus: "needs_review",
    sourceSummary,
    aliases: [alias(scientificName, "scientific", 10), alias(commonName, "common", 10), ...aliases],
  };
}

function genus(
  profileKey: string,
  displayName: string,
  wateringIntervalDaysDefault: number,
  range: [number, number],
  drynessPreference: DrynessPreference,
  wateringGuidance: string,
  aliases: CareProfileAliasFixture[] = [],
): CareProfileFixture {
  return {
    profileKey,
    profileLevel: "genus",
    displayName,
    acceptedScientificName: displayName,
    acceptedCommonName: displayName,
    taxonRank: "genus",
    wateringIntervalDaysDefault,
    wateringIntervalDaysMin: range[0],
    wateringIntervalDaysMax: range[1],
    drynessPreference,
    wateringGuidance,
    beginnerNote: "Genus-level starter for cases where exact species is uncertain.",
    matchConfidence: "medium",
    reviewStatus: "needs_review",
    sourceSummary,
    aliases: [alias(displayName, "genus", 10), ...aliases],
  };
}

function genusCommon(
  profileKey: string,
  displayName: string,
  scientificGenus: string,
  commonName: string,
  wateringIntervalDaysDefault: number,
  range: [number, number],
  drynessPreference: DrynessPreference,
  wateringGuidance: string,
  aliases: CareProfileAliasFixture[] = [],
): CareProfileFixture {
  return {
    profileKey,
    profileLevel: "genus",
    displayName,
    acceptedScientificName: scientificGenus,
    acceptedCommonName: commonName,
    taxonRank: "genus",
    wateringIntervalDaysDefault,
    wateringIntervalDaysMin: range[0],
    wateringIntervalDaysMax: range[1],
    drynessPreference,
    wateringGuidance,
    beginnerNote: "Common houseplant starter profile for editable watering setup.",
    matchConfidence: "medium",
    reviewStatus: "needs_review",
    sourceSummary,
    aliases: [
      alias(scientificGenus, "genus", 10),
      alias(commonName, "common", 10),
      ...aliases,
    ],
  };
}

function careGroup(
  profileKey: string,
  displayName: string,
  wateringIntervalDaysDefault: number,
  range: [number, number],
  drynessPreference: DrynessPreference,
  wateringGuidance: string,
  aliases: CareProfileAliasFixture[],
  profileLevel: CareProfileLevel = "care_group",
): CareProfileFixture {
  return {
    profileKey,
    profileLevel,
    displayName,
    acceptedScientificName: null,
    acceptedCommonName: displayName,
    taxonRank: null,
    wateringIntervalDaysDefault,
    wateringIntervalDaysMin: range[0],
    wateringIntervalDaysMax: range[1],
    drynessPreference,
    wateringGuidance,
    beginnerNote: "Care-group starter for conservative setup when identity is broad or uncertain.",
    matchConfidence: "low",
    reviewStatus: "needs_review",
    sourceSummary,
    aliases,
  };
}

export const CARE_PROFILE_FIXTURES: CareProfileFixture[] = [
  species(
    "species-dracaena-trifasciata",
    "Snake plant",
    "Dracaena trifasciata",
    "Snake plant",
    21,
    [14, 28],
    "dry_fully",
    "Check when the soil has dried through most or all of the pot, then water thoroughly and drain.",
    [alias("Sansevieria trifasciata", "synonym", 20), alias("Mother-in-law's tongue", "common", 30)],
  ),
  species(
    "species-epipremnum-aureum",
    "Pothos",
    "Epipremnum aureum",
    "Pothos",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the soil feels dry and the pot feels lighter.",
    [alias("Devil's ivy", "common", 20), alias("Golden pothos", "common", 20), alias("Money plant", "common", 90, true)],
  ),
  species(
    "species-monstera-deliciosa",
    "Monstera",
    "Monstera deliciosa",
    "Monstera",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two feels dry; water deeply and let extra water drain.",
    [alias("Swiss cheese plant", "common", 20)],
  ),
  genusCommon(
    "genus-spathiphyllum",
    "Peace lily",
    "Spathiphyllum",
    "Peace lily",
    7,
    [5, 10],
    "lightly_moist",
    "Check often and water when the surface starts to dry, before the plant wilts hard.",
    [],
  ),
  species(
    "species-zamioculcas-zamiifolia",
    "ZZ plant",
    "Zamioculcas zamiifolia",
    "ZZ plant",
    21,
    [14, 30],
    "dry_fully",
    "Check that the mix is fully dry before watering; this plant stores water and dislikes soggy soil.",
    [alias("Zanzibar gem", "common", 20)],
  ),
  species(
    "species-chlorophytum-comosum",
    "Spider plant",
    "Chlorophytum comosum",
    "Spider plant",
    7,
    [7, 14],
    "dry_top_inch",
    "Check weekly and water when the top inch feels dry.",
    [
      alias("Airplane plant", "common", 20),
      alias("Ribbon plant", "common", 20),
      alias("Spider ivy", "common", 30),
      alias("Variegated spider plant", "common", 30),
      alias("Bonnie spider plant", "common", 30),
      alias("Chlorophytum capense", "scientific", 20),
      alias("Chlorophytum comosum 'Vittatum'", "synonym", 30),
      alias("Chlorophytum comosum 'Variegatum'", "synonym", 30),
    ],
  ),
  species(
    "species-aloe-vera",
    "Aloe vera",
    "Aloe vera",
    "Aloe vera",
    21,
    [14, 30],
    "dry_fully",
    "Let the potting mix dry fully before watering again, then drain well.",
    [alias("Aloe", "common", 20)],
  ),
  species(
    "species-crassula-ovata",
    "Jade plant",
    "Crassula ovata",
    "Jade plant",
    21,
    [14, 30],
    "dry_fully",
    "Check that the mix is dry before watering; thick leaves usually prefer a cautious cadence.",
    [],
  ),
  species(
    "species-ficus-elastica",
    "Rubber plant",
    "Ficus elastica",
    "Rubber plant",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the soil has dried; avoid leaving the pot in standing water.",
    [alias("Rubber tree", "common", 20)],
  ),
  species(
    "species-ficus-lyrata",
    "Fiddle leaf fig",
    "Ficus lyrata",
    "Fiddle leaf fig",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the soil is dry; water evenly and let the pot drain.",
    [],
  ),
  species(
    "species-pilea-peperomioides",
    "Chinese money plant",
    "Pilea peperomioides",
    "Chinese money plant",
    7,
    [7, 10],
    "dry_top_inch",
    "Check when the top inch feels dry, then water and drain fully.",
    [alias("Money plant", "common", 90, true), alias("Pancake plant", "common", 20)],
  ),
  species(
    "species-nephrolepis-exaltata",
    "Boston fern",
    "Nephrolepis exaltata",
    "Boston fern",
    5,
    [3, 7],
    "evenly_moist",
    "Check every few days and keep the soil evenly moist, not soggy.",
    [],
  ),
  species(
    "species-philodendron-hederaceum",
    "Heartleaf philodendron",
    "Philodendron hederaceum",
    "Heartleaf philodendron",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the soil feels dry; this is a forgiving starter cadence.",
    [],
  ),
  genusCommon(
    "genus-phalaenopsis",
    "Moth orchid",
    "Phalaenopsis",
    "Orchid",
    7,
    [5, 10],
    "special_medium",
    "Check the bark or moss mix; water when it is nearly dry, then let water drain completely.",
    [
      alias("Phalaenopsis orchid", "common", 20),
      alias("Moth orchid", "common", 20),
      alias("Phalaenopsis", "common", 20),
      alias("Grocery store orchid", "common", 30),
      alias("Supermarket orchid", "common", 30),
      alias("Phalaenopsis × singuliflora", "scientific", 20),
      alias("Phalaenopsis x singuliflora", "synonym", 20),
      alias("Phalaenopsis singuliflora", "synonym", 30),
    ],
  ),
  genusCommon(
    "genus-saintpaulia",
    "African violet",
    "Saintpaulia",
    "African violet",
    7,
    [5, 10],
    "lightly_moist",
    "Check when the surface starts to dry and water carefully without soaking the leaves.",
    [alias("Streptocarpus sect. Saintpaulia", "synonym", 20)],
  ),
  species(
    "species-hedera-helix",
    "English ivy",
    "Hedera helix",
    "English ivy",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; avoid letting the pot stay soggy.",
    [],
  ),
  genusCommon(
    "genus-dieffenbachia",
    "Dieffenbachia",
    "Dieffenbachia",
    "Dumb cane",
    7,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch feels dry; water evenly and avoid letting the pot stay soggy.",
    [alias("Dieffenbachia", "common", 10)],
  ),
  genus(
    "genus-aglaonema",
    "Aglaonema",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two dries; keep the cadence moderate and drain well.",
    [alias("Chinese evergreen", "common", 10)],
  ),
  species(
    "species-chamaedorea-elegans",
    "Parlor palm",
    "Chamaedorea elegans",
    "Parlor palm",
    7,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch dries and water evenly through the pot.",
    [alias("Neanthe bella palm", "common", 30)],
  ),
  species(
    "species-dypsis-lutescens",
    "Areca palm",
    "Dypsis lutescens",
    "Areca palm",
    7,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch dries; water thoroughly and let extra water drain.",
    [alias("Butterfly palm", "common", 20), alias("Golden cane palm", "common", 30)],
  ),
  species(
    "species-strelitzia-reginae",
    "Bird of paradise",
    "Strelitzia reginae",
    "Bird of paradise",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper soil has dried; water deeply and drain well.",
    [alias("Orange bird of paradise", "common", 30)],
  ),
  species(
    "species-curio-rowleyanus",
    "String of pearls",
    "Curio rowleyanus",
    "String of pearls",
    21,
    [14, 30],
    "dry_fully",
    "Let the potting mix dry fully before watering; pearls can rot if kept wet.",
    [alias("Senecio rowleyanus", "synonym", 20), alias("Pearl plant", "common", 30)],
  ),
  genusCommon(
    "genus-calathea-goeppertia",
    "Calathea group",
    "Goeppertia",
    "Calathea",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist, but avoid leaving the pot soggy.",
    [alias("Calathea", "genus", 10), alias("Prayer plant", "common", 80, true)],
  ),
  species(
    "species-maranta-leuconeura",
    "Prayer plant",
    "Maranta leuconeura",
    "Red prayer plant",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and water when the surface starts to dry; avoid hard dry-downs.",
    [alias("Red prayer plant", "common", 30), alias("Prayer plant", "common", 80, true)],
  ),
  species(
    "species-anthurium-andraeanum",
    "Anthurium",
    "Anthurium andraeanum",
    "Anthurium",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and keep the mix airy.",
    [alias("Flamingo flower", "common", 20)],
  ),
  species(
    "species-codiaeum-variegatum",
    "Croton",
    "Codiaeum variegatum",
    "Croton",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and avoid letting it sit dry too long.",
    [alias("Garden croton", "common", 20)],
  ),
  genusCommon(
    "genus-heptapleurum-schefflera",
    "Umbrella plant",
    "Heptapleurum",
    "Umbrella plant",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper soil has dried; water thoroughly and drain well.",
    [alias("Schefflera", "synonym", 20), alias("Dwarf umbrella tree", "common", 30)],
  ),
  species(
    "species-tradescantia-zebrina",
    "Tradescantia zebrina",
    "Tradescantia zebrina",
    "Wandering dude",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and avoid soggy soil.",
    [alias("Inch plant", "common", 20), alias("Wandering plant", "common", 30)],
  ),
  genusCommon(
    "genus-syngonium",
    "Syngonium",
    "Syngonium",
    "Arrowhead plant",
    7,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and drain well.",
    [alias("Arrowhead vine", "common", 20), alias("Nephthytis", "synonym", 40)],
  ),
  species(
    "species-scindapsus-pictus",
    "Satin pothos",
    "Scindapsus pictus",
    "Satin pothos",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix has dried; avoid keeping it soggy.",
    [alias("Silver pothos", "common", 20), alias("Silver satin pothos", "common", 30)],
  ),
  species(
    "species-rhaphidophora-tetrasperma",
    "Mini monstera",
    "Rhaphidophora tetrasperma",
    "Mini monstera",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two dries; water thoroughly and drain.",
    [alias("Monstera minima", "common", 30)],
  ),
  genus(
    "genus-dischidia",
    "Dischidia",
    14,
    [10, 21],
    "dry_mostly",
    "Check when most of the mix has dried; water lightly and drain well.",
    [alias("String of nickels", "common", 20)],
  ),
  genus(
    "genus-begonia",
    "Begonia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the surface starts to dry; keep evenly damp but not soggy.",
    [alias("Rex begonia", "common", 20), alias("Angel wing begonia", "common", 80, true)],
  ),
  species(
    "species-fittonia-albivenis",
    "Nerve plant",
    "Fittonia albivenis",
    "Nerve plant",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist; avoid letting it dry hard.",
    [alias("Fittonia", "common", 20)],
  ),
  genus(
    "genus-alocasia",
    "Alocasia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; keep the mix airy and avoid standing water.",
    [alias("Elephant ear", "common", 40, true)],
  ),
  genus(
    "genus-colocasia",
    "Colocasia",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist, especially in bright warm conditions.",
    [alias("Elephant ear", "common", 40, true), alias("Taro", "common", 30)],
  ),
  genus(
    "genus-haworthia",
    "Haworthia",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; use a cautious succulent cadence.",
    [alias("Zebra haworthia", "common", 20), alias("Zebra plant", "common", 80, true)],
  ),
  genus(
    "genus-echeveria",
    "Echeveria",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering and keep water out of the rosette.",
    [alias("Hen and chicks", "common", 50, true)],
  ),
  genusCommon(
    "genus-schlumbergera",
    "Holiday cactus",
    "Schlumbergera",
    "Holiday cactus",
    14,
    [10, 21],
    "dry_top_half",
    "Check when the upper mix dries; this cactus prefers less dry-down than desert cacti.",
    [alias("Christmas cactus", "common", 20), alias("Thanksgiving cactus", "common", 20)],
  ),
  species(
    "species-beaucarnea-recurvata",
    "Ponytail palm",
    "Beaucarnea recurvata",
    "Ponytail palm",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; the swollen base stores water.",
    [alias("Elephant foot plant", "common", 30)],
  ),
  genus(
    "genus-yucca",
    "Yucca",
    21,
    [14, 30],
    "dry_fully",
    "Check that most or all of the mix has dried before watering.",
    [alias("Yucca cane", "common", 20), alias("Spineless yucca", "common", 30)],
  ),
  species(
    "species-aspidistra-elatior",
    "Cast iron plant",
    "Aspidistra elatior",
    "Cast iron plant",
    14,
    [10, 21],
    "dry_mostly",
    "Check when most of the mix has dried; this plant prefers a cautious cadence.",
    [alias("Bar room plant", "common", 30)],
  ),
  species(
    "species-hypoestes-phyllostachya",
    "Polka dot plant",
    "Hypoestes phyllostachya",
    "Polka dot plant",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and water when the surface starts to dry; avoid hard wilting.",
    [alias("Freckle face plant", "common", 30)],
  ),
  species(
    "species-monstera-adansonii",
    "Swiss cheese vine",
    "Monstera adansonii",
    "Swiss cheese vine",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two dries; water thoroughly and let extra water drain.",
    [alias("Adanson's monstera", "common", 20), alias("Monstera friedrichsthalii", "synonym", 30)],
  ),
  species(
    "species-epipremnum-pinnatum",
    "Cebu blue pothos",
    "Epipremnum pinnatum",
    "Cebu blue pothos",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix has dried; water thoroughly and drain well.",
    [alias("Dragon tail pothos", "common", 30), alias("Blue pothos", "common", 30)],
  ),
  species(
    "species-scindapsus-treubii",
    "Scindapsus treubii",
    "Scindapsus treubii",
    "Scindapsus treubii",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix has dried; avoid keeping the pot soggy.",
    [alias("Moonlight scindapsus", "common", 20), alias("Scindapsus treubii Moonlight", "common", 30), alias("Dark form scindapsus", "common", 30)],
  ),
  species(
    "species-philodendron-erubescens",
    "Philodendron erubescens group",
    "Philodendron erubescens",
    "Philodendron erubescens group",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the soil has dried; water evenly and drain well.",
    [alias("Pink princess philodendron", "common", 20), alias("Imperial red philodendron", "common", 20), alias("Rojo congo philodendron", "common", 20), alias("Blushing philodendron", "common", 30)],
  ),
  species(
    "species-philodendron-micans",
    "Philodendron micans",
    "Philodendron hederaceum var. hederaceum",
    "Philodendron micans",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix dries; keep the cadence moderate and drain well.",
    [alias("Philodendron micans", "synonym", 20), alias("Velvet leaf philodendron", "common", 20), alias("Velvet philodendron", "common", 30)],
  ),
  species(
    "species-philodendron-gloriosum",
    "Philodendron gloriosum",
    "Philodendron gloriosum",
    "Philodendron gloriosum",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two dries; water evenly and keep the mix airy.",
    [alias("Gloriosum philodendron", "common", 20)],
  ),
  species(
    "species-thaumatophyllum-bipinnatifidum",
    "Split-leaf philodendron",
    "Thaumatophyllum bipinnatifidum",
    "Split-leaf philodendron",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper soil has dried; water deeply and let extra water drain.",
    [alias("Philodendron bipinnatifidum", "synonym", 20), alias("Tree philodendron", "common", 20), alias("Lacy tree philodendron", "common", 30)],
  ),
  species(
    "species-thaumatophyllum-xanadu",
    "Xanadu philodendron",
    "Thaumatophyllum xanadu",
    "Xanadu philodendron",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper soil has dried; water evenly and drain well.",
    [alias("Philodendron xanadu", "synonym", 20), alias("Xanadu", "common", 20)],
  ),
  species(
    "species-anthurium-clarinervium",
    "Velvet cardboard anthurium",
    "Anthurium clarinervium",
    "Velvet cardboard anthurium",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and keep the mix airy.",
    [alias("Anthurium clarinervium", "common", 20)],
  ),
  species(
    "species-anthurium-crystallinum",
    "Crystal anthurium",
    "Anthurium crystallinum",
    "Crystal anthurium",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and keep the mix airy.",
    [alias("Anthurium crystallinum", "common", 20)],
  ),
  genus(
    "genus-homalomena",
    "Homalomena",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and avoid standing water.",
    [alias("Queen of hearts plant", "common", 30), alias("Emerald gem plant", "common", 30)],
  ),
  genus(
    "genus-amydrium",
    "Amydrium",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper mix has dried; water thoroughly and drain well.",
    [alias("Spiderman monstera", "common", 30)],
  ),
  species(
    "species-epipremnum-amplissimum",
    "Epipremnum amplissimum",
    "Epipremnum amplissimum",
    "Epipremnum amplissimum",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix dries; water thoroughly and drain well.",
    [alias("Silver streak pothos", "common", 30)],
  ),
  species(
    "species-rhaphidophora-decursiva",
    "Rhaphidophora decursiva",
    "Rhaphidophora decursiva",
    "Rhaphidophora decursiva",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two dries; water thoroughly and drain.",
    [alias("Dragon tail plant", "common", 30), alias("Creeping philodendron", "common", 40)],
  ),
  species(
    "species-alocasia-amazonica",
    "African mask alocasia",
    "Alocasia x amazonica",
    "African mask alocasia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; keep the mix airy and avoid letting the pot sit wet.",
    [alias("Alocasia amazonica", "synonym", 20), alias("African mask plant", "common", 20), alias("Alocasia Polly", "common", 30)],
  ),
  species(
    "species-alocasia-reginula",
    "Black velvet alocasia",
    "Alocasia reginula",
    "Black velvet alocasia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water cautiously and keep the mix airy.",
    [alias("Black velvet", "common", 30)],
  ),
  species(
    "species-alocasia-zebrina",
    "Alocasia zebrina",
    "Alocasia zebrina",
    "Alocasia zebrina",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and drain well.",
    [alias("Zebra alocasia", "common", 20), alias("Zebra plant", "common", 80, true)],
  ),
  genus(
    "genus-caladium",
    "Caladium",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist while actively growing; avoid soggy soil.",
    [alias("Angel wings", "common", 30), alias("Heart of Jesus", "common", 30), alias("Elephant ear", "common", 40, true)],
  ),
  species(
    "species-hoya-carnosa",
    "Wax plant",
    "Hoya carnosa",
    "Wax plant",
    14,
    [10, 21],
    "dry_mostly",
    "Check that most of the potting mix is dry before watering; drain well.",
    [alias("Hoya carnosa", "common", 20), alias("Porcelain flower", "common", 30), alias("Krimson queen hoya", "common", 40), alias("Krimson princess hoya", "common", 40)],
  ),
  species(
    "species-hoya-carnosa-compacta",
    "Hindu rope hoya",
    "Hoya carnosa compacta",
    "Hindu rope hoya",
    14,
    [10, 21],
    "dry_mostly",
    "Check that most of the mix is dry; water carefully through the dense vines and drain well.",
    [alias("Hoya compacta", "synonym", 20), alias("Hindu rope plant", "common", 20), alias("Rope hoya", "common", 30)],
  ),
  species(
    "species-hoya-kerrii",
    "Sweetheart hoya",
    "Hoya kerrii",
    "Sweetheart hoya",
    14,
    [10, 21],
    "dry_mostly",
    "Check that most of the mix is dry before watering; small pots may dry faster.",
    [alias("Heart hoya", "common", 20), alias("Valentine hoya", "common", 30), alias("Lucky heart plant", "common", 30)],
  ),
  species(
    "species-peperomia-obtusifolia",
    "Baby rubber plant",
    "Peperomia obtusifolia",
    "Baby rubber plant",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix dries; water lightly and drain well.",
    [alias("Pepper face", "common", 30), alias("American rubber plant", "common", 30)],
  ),
  species(
    "species-peperomia-caperata",
    "Ripple peperomia",
    "Peperomia caperata",
    "Ripple peperomia",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix dries; avoid letting the pot stay soggy.",
    [alias("Emerald ripple peperomia", "common", 20)],
  ),
  species(
    "species-peperomia-argyreia",
    "Watermelon peperomia",
    "Peperomia argyreia",
    "Watermelon peperomia",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the mix dries; water lightly and drain well.",
    [],
  ),
  species(
    "species-ceropegia-woodii",
    "String of hearts",
    "Ceropegia woodii",
    "String of hearts",
    14,
    [10, 21],
    "dry_mostly",
    "Check that most of the mix is dry before watering; avoid keeping the tubers wet.",
    [alias("Rosary vine", "common", 20), alias("Chain of hearts", "common", 30)],
  ),
  species(
    "species-kalanchoe-blossfeldiana",
    "Flaming Katy",
    "Kalanchoe blossfeldiana",
    "Flaming Katy",
    14,
    [10, 21],
    "dry_mostly",
    "Check that most or all of the mix has dried before watering; drain well.",
    [alias("Florist kalanchoe", "common", 20), alias("Christmas kalanchoe", "common", 30)],
  ),
  species(
    "species-kalanchoe-tomentosa",
    "Panda plant",
    "Kalanchoe tomentosa",
    "Panda plant",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; fuzzy succulent leaves dislike staying wet.",
    [alias("Chocolate soldier", "common", 20)],
  ),
  species(
    "species-sedum-morganianum",
    "Burro's tail",
    "Sedum morganianum",
    "Burro's tail",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; water gently and drain well.",
    [alias("Donkey tail", "common", 20), alias("Burros tail", "common", 30)],
  ),
  species(
    "species-portulacaria-afra",
    "Elephant bush",
    "Portulacaria afra",
    "Elephant bush",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; use a cautious succulent cadence.",
    [alias("Dwarf jade", "common", 20), alias("Spekboom", "common", 30)],
  ),
  species(
    "species-curio-herreanus",
    "String of tears",
    "Curio herreanus",
    "String of tears",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; trailing beads can rot if kept wet.",
    [alias("Senecio herreianus", "synonym", 20), alias("String of raindrops", "common", 30)],
  ),
  species(
    "species-crassula-perforata",
    "String of buttons",
    "Crassula perforata",
    "String of buttons",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; drain well and avoid frequent sips.",
    [alias("Necklace vine", "common", 30)],
  ),
  genus(
    "genus-aeonium",
    "Aeonium",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; adjust slower during rest periods.",
    [alias("Tree houseleek", "common", 30)],
  ),
  genus(
    "genus-lithops",
    "Lithops",
    35,
    [28, 45],
    "dry_fully",
    "Use a very cautious cadence and water only after the mix is fully dry.",
    [alias("Living stones", "common", 20), alias("Pebble plant", "common", 30)],
  ),
  genus(
    "genus-gasteria",
    "Gasteria",
    21,
    [14, 30],
    "dry_fully",
    "Let the mix dry fully before watering; drain well and avoid standing water.",
    [alias("Ox tongue", "common", 30)],
  ),
  species(
    "species-asplenium-nidus",
    "Bird's nest fern",
    "Asplenium nidus",
    "Bird's nest fern",
    5,
    [3, 7],
    "evenly_moist",
    "Check every few days and keep evenly moist, but avoid water sitting in the crown.",
    [alias("Birds nest fern", "common", 30)],
  ),
  genus(
    "genus-adiantum",
    "Maidenhair fern",
    3,
    [2, 5],
    "evenly_moist",
    "Check very often and keep evenly moist; avoid letting the pot dry hard.",
    [alias("Adiantum", "genus", 10), alias("Maidenhair fern", "common", 10)],
  ),
  genus(
    "genus-pteris",
    "Brake fern",
    5,
    [3, 7],
    "evenly_moist",
    "Check often and keep evenly moist with good drainage.",
    [alias("Pteris", "genus", 10), alias("Table fern", "common", 30)],
  ),
  genus(
    "genus-platycerium",
    "Staghorn fern",
    7,
    [5, 10],
    "special_medium",
    "Check the mount or loose mix; water when it is starting to dry but not bone dry.",
    [alias("Platycerium", "genus", 10), alias("Elkhorn fern", "common", 30)],
  ),
  genus(
    "genus-selaginella",
    "Selaginella",
    3,
    [2, 5],
    "evenly_moist",
    "Check very often and keep evenly moist; this plant declines after hard dry-downs.",
    [alias("Spike moss", "common", 20), alias("Club moss", "common", 30)],
  ),
  species(
    "species-soleirolia-soleirolii",
    "Baby's tears",
    "Soleirolia soleirolii",
    "Baby's tears",
    3,
    [2, 5],
    "evenly_moist",
    "Check very often and keep evenly moist; small pots can dry quickly.",
    [alias("Baby tears plant", "common", 20), alias("Mind-your-own-business", "common", 30)],
  ),
  species(
    "species-howea-forsteriana",
    "Kentia palm",
    "Howea forsteriana",
    "Kentia palm",
    10,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch or two dries; water evenly through the pot.",
    [alias("Thatch palm", "common", 30)],
  ),
  species(
    "species-rhapis-excelsa",
    "Lady palm",
    "Rhapis excelsa",
    "Lady palm",
    7,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and avoid soggy soil.",
    [alias("Broadleaf lady palm", "common", 20)],
  ),
  species(
    "species-caryota-mitis",
    "Fishtail palm",
    "Caryota mitis",
    "Fishtail palm",
    7,
    [7, 14],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and drain well.",
    [alias("Clustering fishtail palm", "common", 30)],
  ),
  species(
    "species-dracaena-fragrans",
    "Corn plant",
    "Dracaena fragrans",
    "Corn plant",
    14,
    [10, 21],
    "dry_mostly",
    "Check when most of the soil has dried; water thoroughly and drain, and avoid keeping the cane or roots soggy.",
    [
      alias("Cornstalk dracaena", "common", 20),
      alias("Mass cane", "common", 20),
      alias("Cane plant", "common", 30),
      alias("Happy plant", "common", 30),
      alias("Dracaena massangeana", "synonym", 30),
      alias("Dracaena fragrans 'Massangeana'", "synonym", 30),
    ],
  ),
  species(
    "species-dracaena-marginata",
    "Dragon tree",
    "Dracaena marginata",
    "Dragon tree",
    14,
    [10, 21],
    "dry_mostly",
    "Check when most of the soil has dried; this plant prefers a cautious cadence.",
    [alias("Madagascar dragon tree", "common", 20), alias("Dracaena reflexa var. angustifolia", "synonym", 30)],
  ),
  species(
    "species-dracaena-reflexa",
    "Song of India",
    "Dracaena reflexa",
    "Song of India",
    14,
    [10, 21],
    "dry_mostly",
    "Check when most of the soil has dried; avoid keeping roots constantly wet.",
    [alias("Pleomele", "common", 30), alias("Song of Jamaica", "common", 30)],
  ),
  species(
    "species-cordyline-fruticosa",
    "Ti plant",
    "Cordyline fruticosa",
    "Ti plant",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and avoid hard dry-downs.",
    [alias("Hawaiian ti plant", "common", 20), alias("Good luck plant", "common", 30)],
  ),
  genus(
    "genus-aeschynanthus",
    "Lipstick plant",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper mix has dried; water thoroughly and drain well.",
    [alias("Aeschynanthus", "genus", 10), alias("Lipstick vine", "common", 20)],
  ),
  genus(
    "genus-nematanthus",
    "Goldfish plant",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper mix has dried; water evenly and drain well.",
    [alias("Nematanthus", "genus", 10), alias("Guppy plant", "common", 30)],
  ),
  genus(
    "genus-columnea",
    "Columnea",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the upper mix has dried; water evenly and avoid soggy soil.",
    [alias("Flying goldfish plant", "common", 30)],
  ),
  species(
    "species-oxalis-triangularis",
    "Purple shamrock",
    "Oxalis triangularis",
    "Purple shamrock",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly, and pause if the plant goes dormant.",
    [alias("False shamrock", "common", 20), alias("Love plant", "common", 30)],
  ),
  species(
    "species-cyclamen-persicum",
    "Florist's cyclamen",
    "Cyclamen persicum",
    "Florist's cyclamen",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist while actively growing; avoid soaking the crown.",
    [alias("Persian cyclamen", "common", 20), alias("Cyclamen", "common", 30)],
  ),
  species(
    "species-begonia-maculata",
    "Polka dot begonia",
    "Begonia maculata",
    "Polka dot begonia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the surface starts to dry; keep evenly damp but not soggy.",
    [alias("Begonia maculata Wightii", "common", 30), alias("Angel wing begonia", "common", 80, true)],
  ),
  species(
    "species-dionaea-muscipula",
    "Venus flytrap",
    "Dionaea muscipula",
    "Venus flytrap",
    3,
    [2, 5],
    "special_medium",
    "Keep the special medium consistently wet with mineral-free water; do not let it dry out.",
    [alias("Venus fly trap", "common", 20)],
  ),
  genus(
    "genus-dendrobium",
    "Dendrobium orchid",
    7,
    [5, 10],
    "special_medium",
    "Check the bark or moss mix; water when the medium is close to dry, then drain completely.",
    [alias("Dendrobium", "genus", 10), alias("Dendrobium orchid", "common", 20)],
  ),
  genus(
    "genus-oncidium",
    "Oncidium orchid",
    7,
    [5, 10],
    "special_medium",
    "Check the bark or moss mix; water when it is starting to dry, then drain well.",
    [alias("Oncidium", "genus", 10), alias("Oncidium orchid", "common", 20), alias("Dancing lady orchid", "common", 30)],
  ),
  genus(
    "genus-cattleya",
    "Cattleya orchid",
    7,
    [5, 10],
    "special_medium",
    "Check the bark or coarse mix; water when it is nearly dry, then drain completely.",
    [alias("Cattleya", "genus", 10), alias("Cattleya orchid", "common", 20), alias("Corsage orchid", "common", 30)],
  ),
  genus(
    "genus-paphiopedilum",
    "Paphiopedilum orchid",
    7,
    [5, 10],
    "special_medium",
    "Check the orchid mix often and water when it is just starting to dry; drain well.",
    [alias("Paphiopedilum", "genus", 10), alias("Paphiopedilum orchid", "common", 20), alias("Lady slipper orchid", "common", 30)],
  ),
  genus(
    "genus-cymbidium",
    "Cymbidium orchid",
    7,
    [5, 10],
    "special_medium",
    "Check the orchid mix and water when it is starting to dry; let extra water drain.",
    [alias("Cymbidium", "genus", 10), alias("Cymbidium orchid", "common", 20), alias("Boat orchid", "common", 30)],
  ),
  species(
    "species-pachira-aquatica",
    "Money tree",
    "Pachira aquatica",
    "Money tree",
    10,
    [7, 14],
    "dry_top_half",
    "Check when the top half of the soil has dried; water thoroughly and drain well.",
    [alias("Guiana chestnut", "common", 30), alias("Malabar chestnut", "common", 30), alias("Money plant", "common", 90, true)],
  ),
  species(
    "species-dracaena-sanderiana",
    "Lucky bamboo",
    "Dracaena sanderiana",
    "Lucky bamboo",
    7,
    [5, 10],
    "special_medium",
    "Check the water or potting medium often; keep roots lightly moist without stagnant water.",
    [alias("Ribbon dracaena", "common", 30), alias("Bamboo plant", "common", 90, true)],
  ),
  species(
    "species-araucaria-heterophylla",
    "Norfolk Island pine",
    "Araucaria heterophylla",
    "Norfolk Island pine",
    7,
    [5, 10],
    "lightly_moist",
    "Check when the surface starts to dry; keep lightly moist but not soggy.",
    [alias("Norfolk pine", "common", 20), alias("Living Christmas tree", "common", 30)],
  ),
  species(
    "species-stromanthe-thalia",
    "Triostar stromanthe",
    "Stromanthe thalia",
    "Triostar stromanthe",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist; avoid hard dry-downs and standing water.",
    [alias("Stromanthe sanguinea", "synonym", 20), alias("Stromanthe Triostar", "common", 20), alias("Tricolor stromanthe", "common", 30), alias("Prayer plant", "common", 80, true)],
  ),
  genus(
    "genus-ctenanthe",
    "Ctenanthe",
    5,
    [3, 7],
    "lightly_moist",
    "Check often and keep lightly moist, but do not leave the pot soggy.",
    [alias("Never never plant", "common", 20), alias("Prayer plant", "common", 80, true)],
  ),
  species(
    "species-polyscias-fruticosa",
    "Ming aralia",
    "Polyscias fruticosa",
    "Ming aralia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and avoid soggy soil.",
    [alias("Aralia fruticosa", "synonym", 30)],
  ),
  species(
    "species-plerandra-elegantissima",
    "False aralia",
    "Plerandra elegantissima",
    "False aralia",
    7,
    [5, 10],
    "dry_top_inch",
    "Check when the top inch dries; water evenly and drain well.",
    [alias("Schefflera elegantissima", "synonym", 20), alias("Dizygotheca elegantissima", "synonym", 30), alias("Threadleaf aralia", "common", 30)],
  ),
  genus(
    "genus-nepenthes",
    "Tropical pitcher plant",
    5,
    [3, 7],
    "special_medium",
    "Keep the special medium lightly moist with mineral-free water; drain rather than leave waterlogged.",
    [alias("Nepenthes", "genus", 10), alias("Monkey cup", "common", 30)],
  ),
  genus("genus-philodendron", "Philodendron", 10, [7, 14], "dry_top_half", "Check when the top half of the soil has dried; avoid soggy soil."),
  genus("genus-dracaena", "Dracaena", 14, [10, 21], "dry_mostly", "Check when most of the soil has dried; many dracaenas prefer a cautious cadence."),
  genus("genus-peperomia", "Peperomia", 10, [7, 14], "dry_top_half", "Check when the top half is dry; water lightly and drain well."),
  genus("genus-ficus", "Ficus", 10, [7, 14], "dry_top_half", "Check when the upper soil has dried; keep the cadence steady and avoid soggy roots."),
  genus("genus-hoya", "Hoya", 14, [10, 21], "dry_mostly", "Check that most of the potting mix is dry before watering."),
  careGroup("care-group-succulent-like", "Succulent-like houseplant", 21, [14, 30], "dry_fully", "Start cautiously: check that the mix is fully dry before watering.", [
    alias("Succulent", "group", 10),
    alias("Succulent-like", "group", 20),
  ]),
  careGroup("care-group-cactus", "Cactus / very dry houseplant", 28, [21, 35], "dry_fully", "Check infrequently and water only after the mix has fully dried.", [
    alias("Cactus", "group", 10),
  ]),
  careGroup("care-group-moderate-tropical", "Moderate tropical houseplant", 7, [7, 14], "dry_top_inch", "Start by checking weekly and water when the top inch feels dry.", [
    alias("Tropical houseplant", "group", 10),
  ]),
  careGroup("care-group-moisture-loving-tropical", "Moisture-loving tropical houseplant", 5, [3, 7], "lightly_moist", "Check often and keep lightly moist, but do not leave the pot soggy.", [
    alias("Moisture-loving tropical", "group", 10),
  ]),
  careGroup("care-group-fern", "Fern / evenly moist houseplant", 5, [3, 7], "evenly_moist", "Check often and keep evenly moist with good drainage.", [
    alias("Fern", "group", 10),
  ]),
  careGroup("care-group-orchid-bark", "Orchid in bark mix", 7, [5, 10], "special_medium", "Check the bark mix and water when it is nearly dry, then drain completely.", [
    alias("Orchid in bark", "group", 10),
  ]),
  careGroup("care-group-palm", "Palm houseplant", 7, [7, 14], "dry_top_inch", "Check when the top inch dries and water evenly through the pot.", [
    alias("Palm", "group", 10),
  ]),
  careGroup("fallback-unknown-conservative", "Unknown conservative starter", 7, [5, 10], "unknown_conservative", "Start by checking every week and water only when the top inch feels dry; adjust after you learn the plant.", [
    alias("Unknown houseplant", "group", 10),
  ], "fallback"),
];

export function careProfileFixtureAliasRows() {
  return CARE_PROFILE_FIXTURES.flatMap((profile) =>
    profile.aliases.map((profileAlias) => ({
      profileKey: profile.profileKey,
      alias: profileAlias.alias,
      normalizedAlias: normalizeCareProfileName(profileAlias.alias),
      aliasType: profileAlias.aliasType,
      priority: profileAlias.priority ?? 50,
      allowAmbiguous: profileAlias.allowAmbiguous ?? false,
    })),
  );
}
