import type { CareProfileWithAliases } from "@/lib/care-profiles/types";

const now = "2026-05-18T00:00:00.000Z";

function profile(
  overrides: Omit<CareProfileWithAliases, "id" | "created_at" | "updated_at" | "aliases"> & {
    aliases: Array<Omit<CareProfileWithAliases["aliases"][number], "id" | "care_profile_id" | "created_at">>;
  },
): CareProfileWithAliases {
  const id = overrides.profile_key;

  return {
    id,
    created_at: now,
    updated_at: now,
    ...overrides,
    aliases: overrides.aliases.map((alias, index) => ({
      id: `${id}-alias-${index + 1}`,
      care_profile_id: id,
      created_at: now,
      ...alias,
    })),
  };
}

export const MINIMAL_CARE_PROFILES: CareProfileWithAliases[] = [
  profile({
    profile_key: "species-dracaena-trifasciata",
    profile_level: "species",
    display_name: "Snake plant",
    accepted_scientific_name: "Dracaena trifasciata",
    accepted_common_name: "Snake plant",
    taxon_rank: "species",
    watering_interval_days_default: 21,
    watering_interval_days_min: 14,
    watering_interval_days_max: 28,
    dryness_preference: "dry_fully",
    watering_guidance: "Check the soil and water only when it has dried through most or all of the pot.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "A conservative starter profile for drought-tolerant snake plants.",
    toxicity_note: null,
    match_confidence: "medium",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [
      {
        alias: "Dracaena trifasciata",
        normalized_alias: "dracaena trifasciata",
        alias_type: "scientific",
        priority: 10,
      },
      {
        alias: "Sansevieria trifasciata",
        normalized_alias: "sansevieria trifasciata",
        alias_type: "synonym",
        priority: 20,
      },
      { alias: "Snake plant", normalized_alias: "snake plant", alias_type: "common", priority: 10 },
      {
        alias: "Mother-in-law's tongue",
        normalized_alias: "mother in laws tongue",
        alias_type: "common",
        priority: 30,
      },
    ],
  }),
  profile({
    profile_key: "species-epipremnum-aureum",
    profile_level: "species",
    display_name: "Pothos",
    accepted_scientific_name: "Epipremnum aureum",
    accepted_common_name: "Pothos",
    taxon_rank: "species",
    watering_interval_days_default: 10,
    watering_interval_days_min: 7,
    watering_interval_days_max: 14,
    dryness_preference: "dry_top_half",
    watering_guidance: "Check the soil and water when the top half feels dry and the pot feels lighter.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "A forgiving trailing houseplant starter profile.",
    toxicity_note: null,
    match_confidence: "medium",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [
      {
        alias: "Epipremnum aureum",
        normalized_alias: "epipremnum aureum",
        alias_type: "scientific",
        priority: 10,
      },
      { alias: "Pothos", normalized_alias: "pothos", alias_type: "common", priority: 10 },
      { alias: "Devil's ivy", normalized_alias: "devils ivy", alias_type: "common", priority: 20 },
      { alias: "Money plant", normalized_alias: "money plant", alias_type: "common", priority: 90 },
    ],
  }),
  profile({
    profile_key: "species-pilea-peperomioides",
    profile_level: "species",
    display_name: "Chinese money plant",
    accepted_scientific_name: "Pilea peperomioides",
    accepted_common_name: "Chinese money plant",
    taxon_rank: "species",
    watering_interval_days_default: 7,
    watering_interval_days_min: 7,
    watering_interval_days_max: 10,
    dryness_preference: "dry_top_inch",
    watering_guidance: "Check the soil and water when the top inch feels dry, then let extra water drain fully.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "Included to exercise ambiguity-safe common-name matching.",
    toxicity_note: null,
    match_confidence: "medium",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [
      {
        alias: "Pilea peperomioides",
        normalized_alias: "pilea peperomioides",
        alias_type: "scientific",
        priority: 10,
      },
      {
        alias: "Chinese money plant",
        normalized_alias: "chinese money plant",
        alias_type: "common",
        priority: 10,
      },
      { alias: "Money plant", normalized_alias: "money plant", alias_type: "common", priority: 90 },
    ],
  }),
  profile({
    profile_key: "genus-philodendron",
    profile_level: "genus",
    display_name: "Philodendron",
    accepted_scientific_name: "Philodendron",
    accepted_common_name: "Philodendron",
    taxon_rank: "genus",
    watering_interval_days_default: 10,
    watering_interval_days_min: 7,
    watering_interval_days_max: 14,
    dryness_preference: "dry_top_half",
    watering_guidance: "Check the soil and water when the top half has dried; avoid leaving the pot soggy.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "Genus-level starter for common vining and self-heading philodendrons.",
    toxicity_note: null,
    match_confidence: "medium",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [{ alias: "Philodendron", normalized_alias: "philodendron", alias_type: "genus", priority: 10 }],
  }),
  profile({
    profile_key: "care-group-succulent-like",
    profile_level: "care_group",
    display_name: "Succulent-like houseplant",
    accepted_scientific_name: null,
    accepted_common_name: "Succulent-like houseplant",
    taxon_rank: null,
    watering_interval_days_default: 21,
    watering_interval_days_min: 14,
    watering_interval_days_max: 30,
    dryness_preference: "dry_fully",
    watering_guidance:
      "Start cautiously: check that the mix is fully dry before watering, then water thoroughly and drain.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "Care-group starter for thick-leaved drought-tolerant houseplants.",
    toxicity_note: null,
    match_confidence: "low",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [
      { alias: "Succulent", normalized_alias: "succulent", alias_type: "group", priority: 10 },
      { alias: "Succulent-like", normalized_alias: "succulent like", alias_type: "group", priority: 20 },
    ],
  }),
  profile({
    profile_key: "care-group-moderate-tropical",
    profile_level: "care_group",
    display_name: "Moderate tropical houseplant",
    accepted_scientific_name: null,
    accepted_common_name: "Moderate tropical houseplant",
    taxon_rank: null,
    watering_interval_days_default: 7,
    watering_interval_days_min: 7,
    watering_interval_days_max: 14,
    dryness_preference: "dry_top_inch",
    watering_guidance: "Start by checking weekly and water when the top inch of soil feels dry.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "Care-group starter for common leafy tropical houseplants.",
    toxicity_note: null,
    match_confidence: "low",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [
      {
        alias: "Tropical houseplant",
        normalized_alias: "tropical houseplant",
        alias_type: "group",
        priority: 10,
      },
    ],
  }),
  profile({
    profile_key: "fallback-unknown-conservative",
    profile_level: "fallback",
    display_name: "Unknown conservative starter",
    accepted_scientific_name: null,
    accepted_common_name: "Unknown houseplant",
    taxon_rank: null,
    watering_interval_days_default: 7,
    watering_interval_days_min: 5,
    watering_interval_days_max: 10,
    dryness_preference: "unknown_conservative",
    watering_guidance:
      "Start by checking every week and water only when the top inch feels dry; adjust after you learn how quickly it dries in your home.",
    light_guidance: null,
    soil_pot_drainage_guidance: null,
    humidity_guidance: null,
    seasonal_note: null,
    beginner_note: "Fallback starter for plants without a safe identity or profile match.",
    toxicity_note: null,
    match_confidence: "low",
    review_status: "draft",
    source_summary:
      "Starter reference data for the AI Care Setup foundation; review before broad user-facing rollout.",
    source_links: null,
    last_reviewed_at: null,
    aliases: [
      {
        alias: "Unknown houseplant",
        normalized_alias: "unknown houseplant",
        alias_type: "group",
        priority: 10,
      },
    ],
  }),
];
