-- Generated from src/lib/care-profiles/fixtures.ts.
-- Regenerate with: node scripts/generate-care-profile-seed-sql.mjs

insert into public.care_profiles (
  profile_key,
  profile_level,
  display_name,
  accepted_scientific_name,
  accepted_common_name,
  taxon_rank,
  watering_interval_days_default,
  watering_interval_days_min,
  watering_interval_days_max,
  dryness_preference,
  watering_guidance,
  beginner_note,
  match_confidence,
  review_status,
  source_summary
)
values
  ('species-dracaena-trifasciata', 'species', 'Snake plant', 'Dracaena trifasciata', 'Snake plant', 'species', 21, 14, 28, 'dry_fully', 'Check when the soil has dried through most or all of the pot, then water thoroughly and drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-epipremnum-aureum', 'species', 'Pothos', 'Epipremnum aureum', 'Pothos', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil feels dry and the pot feels lighter.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-monstera-deliciosa', 'species', 'Monstera', 'Monstera deliciosa', 'Monstera', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two feels dry; water deeply and let extra water drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-spathiphyllum', 'genus', 'Peace lily', 'Spathiphyllum', 'Peace lily', 'genus', 7, 5, 10, 'lightly_moist', 'Check often and water when the surface starts to dry, before the plant wilts hard.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-zamioculcas-zamiifolia', 'species', 'ZZ plant', 'Zamioculcas zamiifolia', 'ZZ plant', 'species', 21, 14, 30, 'dry_fully', 'Check that the mix is fully dry before watering; this plant stores water and dislikes soggy soil.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-chlorophytum-comosum', 'species', 'Spider plant', 'Chlorophytum comosum', 'Spider plant', 'species', 7, 7, 14, 'dry_top_inch', 'Check weekly and water when the top inch feels dry.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-aloe-vera', 'species', 'Aloe vera', 'Aloe vera', 'Aloe vera', 'species', 21, 14, 30, 'dry_fully', 'Let the potting mix dry fully before watering again, then drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-crassula-ovata', 'species', 'Jade plant', 'Crassula ovata', 'Jade plant', 'species', 21, 14, 30, 'dry_fully', 'Check that the mix is dry before watering; thick leaves usually prefer a cautious cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-ficus-elastica', 'species', 'Rubber plant', 'Ficus elastica', 'Rubber plant', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil has dried; avoid leaving the pot in standing water.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-ficus-lyrata', 'species', 'Fiddle leaf fig', 'Ficus lyrata', 'Fiddle leaf fig', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil is dry; water evenly and let the pot drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-pilea-peperomioides', 'species', 'Chinese money plant', 'Pilea peperomioides', 'Chinese money plant', 'species', 7, 7, 10, 'dry_top_inch', 'Check when the top inch feels dry, then water and drain fully.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-nephrolepis-exaltata', 'species', 'Boston fern', 'Nephrolepis exaltata', 'Boston fern', 'species', 5, 3, 7, 'evenly_moist', 'Check every few days and keep the soil evenly moist, not soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-philodendron-hederaceum', 'species', 'Heartleaf philodendron', 'Philodendron hederaceum', 'Heartleaf philodendron', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil feels dry; this is a forgiving starter cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-phalaenopsis', 'genus', 'Moth orchid', 'Phalaenopsis', 'Orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the bark or moss mix; water when it is nearly dry, then let water drain completely.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-saintpaulia', 'genus', 'African violet', 'Saintpaulia', 'African violet', 'genus', 7, 5, 10, 'lightly_moist', 'Check when the surface starts to dry and water carefully without soaking the leaves.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-hedera-helix', 'species', 'English ivy', 'Hedera helix', 'English ivy', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; avoid letting the pot stay soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-philodendron', 'genus', 'Philodendron', 'Philodendron', 'Philodendron', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil has dried; avoid soggy soil.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-dracaena', 'genus', 'Dracaena', 'Dracaena', 'Dracaena', 'genus', 14, 10, 21, 'dry_mostly', 'Check when most of the soil has dried; many dracaenas prefer a cautious cadence.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-peperomia', 'genus', 'Peperomia', 'Peperomia', 'Peperomia', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the top half is dry; water lightly and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-ficus', 'genus', 'Ficus', 'Ficus', 'Ficus', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper soil has dried; keep the cadence steady and avoid soggy roots.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-hoya', 'genus', 'Hoya', 'Hoya', 'Hoya', 'genus', 14, 10, 21, 'dry_mostly', 'Check that most of the potting mix is dry before watering.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-succulent-like', 'care_group', 'Succulent-like houseplant', null, 'Succulent-like houseplant', null, 21, 14, 30, 'dry_fully', 'Start cautiously: check that the mix is fully dry before watering.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-cactus', 'care_group', 'Cactus / very dry houseplant', null, 'Cactus / very dry houseplant', null, 28, 21, 35, 'dry_fully', 'Check infrequently and water only after the mix has fully dried.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-moderate-tropical', 'care_group', 'Moderate tropical houseplant', null, 'Moderate tropical houseplant', null, 7, 7, 14, 'dry_top_inch', 'Start by checking weekly and water when the top inch feels dry.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-moisture-loving-tropical', 'care_group', 'Moisture-loving tropical houseplant', null, 'Moisture-loving tropical houseplant', null, 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist, but do not leave the pot soggy.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-fern', 'care_group', 'Fern / evenly moist houseplant', null, 'Fern / evenly moist houseplant', null, 5, 3, 7, 'evenly_moist', 'Check often and keep evenly moist with good drainage.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-orchid-bark', 'care_group', 'Orchid in bark mix', null, 'Orchid in bark mix', null, 7, 5, 10, 'special_medium', 'Check the bark mix and water when it is nearly dry, then drain completely.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-palm', 'care_group', 'Palm houseplant', null, 'Palm houseplant', null, 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries and water evenly through the pot.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('fallback-unknown-conservative', 'fallback', 'Unknown conservative starter', null, 'Unknown conservative starter', null, 7, 5, 10, 'unknown_conservative', 'Start by checking every week and water only when the top inch feels dry; adjust after you learn the plant.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.')
on conflict (profile_key) do update
set
  profile_level = excluded.profile_level,
  display_name = excluded.display_name,
  accepted_scientific_name = excluded.accepted_scientific_name,
  accepted_common_name = excluded.accepted_common_name,
  taxon_rank = excluded.taxon_rank,
  watering_interval_days_default = excluded.watering_interval_days_default,
  watering_interval_days_min = excluded.watering_interval_days_min,
  watering_interval_days_max = excluded.watering_interval_days_max,
  dryness_preference = excluded.dryness_preference,
  watering_guidance = excluded.watering_guidance,
  beginner_note = excluded.beginner_note,
  match_confidence = excluded.match_confidence,
  review_status = excluded.review_status,
  source_summary = excluded.source_summary;

with alias_seed(profile_key, alias, normalized_alias, alias_type, priority) as (
  values
  ('species-dracaena-trifasciata', 'Dracaena trifasciata', 'dracaena trifasciata', 'scientific', 10),
  ('species-dracaena-trifasciata', 'Snake plant', 'snake plant', 'common', 10),
  ('species-dracaena-trifasciata', 'Sansevieria trifasciata', 'sansevieria trifasciata', 'synonym', 20),
  ('species-dracaena-trifasciata', 'Mother-in-law''s tongue', 'mother in laws tongue', 'common', 30),
  ('species-epipremnum-aureum', 'Epipremnum aureum', 'epipremnum aureum', 'scientific', 10),
  ('species-epipremnum-aureum', 'Pothos', 'pothos', 'common', 10),
  ('species-epipremnum-aureum', 'Devil''s ivy', 'devils ivy', 'common', 20),
  ('species-epipremnum-aureum', 'Golden pothos', 'golden pothos', 'common', 20),
  ('species-epipremnum-aureum', 'Money plant', 'money plant', 'common', 90),
  ('species-monstera-deliciosa', 'Monstera deliciosa', 'monstera deliciosa', 'scientific', 10),
  ('species-monstera-deliciosa', 'Monstera', 'monstera', 'common', 10),
  ('species-monstera-deliciosa', 'Swiss cheese plant', 'swiss cheese plant', 'common', 20),
  ('genus-spathiphyllum', 'Spathiphyllum', 'spathiphyllum', 'genus', 10),
  ('genus-spathiphyllum', 'Peace lily', 'peace lily', 'common', 10),
  ('species-zamioculcas-zamiifolia', 'Zamioculcas zamiifolia', 'zamioculcas zamiifolia', 'scientific', 10),
  ('species-zamioculcas-zamiifolia', 'ZZ plant', 'zz plant', 'common', 10),
  ('species-zamioculcas-zamiifolia', 'Zanzibar gem', 'zanzibar gem', 'common', 20),
  ('species-chlorophytum-comosum', 'Chlorophytum comosum', 'chlorophytum comosum', 'scientific', 10),
  ('species-chlorophytum-comosum', 'Spider plant', 'spider plant', 'common', 10),
  ('species-aloe-vera', 'Aloe vera', 'aloe vera', 'scientific', 10),
  ('species-aloe-vera', 'Aloe vera', 'aloe vera', 'common', 10),
  ('species-aloe-vera', 'Aloe', 'aloe', 'common', 20),
  ('species-crassula-ovata', 'Crassula ovata', 'crassula ovata', 'scientific', 10),
  ('species-crassula-ovata', 'Jade plant', 'jade plant', 'common', 10),
  ('species-ficus-elastica', 'Ficus elastica', 'ficus elastica', 'scientific', 10),
  ('species-ficus-elastica', 'Rubber plant', 'rubber plant', 'common', 10),
  ('species-ficus-elastica', 'Rubber tree', 'rubber tree', 'common', 20),
  ('species-ficus-lyrata', 'Ficus lyrata', 'ficus lyrata', 'scientific', 10),
  ('species-ficus-lyrata', 'Fiddle leaf fig', 'fiddle leaf fig', 'common', 10),
  ('species-pilea-peperomioides', 'Pilea peperomioides', 'pilea peperomioides', 'scientific', 10),
  ('species-pilea-peperomioides', 'Chinese money plant', 'chinese money plant', 'common', 10),
  ('species-pilea-peperomioides', 'Money plant', 'money plant', 'common', 90),
  ('species-pilea-peperomioides', 'Pancake plant', 'pancake plant', 'common', 20),
  ('species-nephrolepis-exaltata', 'Nephrolepis exaltata', 'nephrolepis exaltata', 'scientific', 10),
  ('species-nephrolepis-exaltata', 'Boston fern', 'boston fern', 'common', 10),
  ('species-philodendron-hederaceum', 'Philodendron hederaceum', 'philodendron hederaceum', 'scientific', 10),
  ('species-philodendron-hederaceum', 'Heartleaf philodendron', 'heartleaf philodendron', 'common', 10),
  ('genus-phalaenopsis', 'Phalaenopsis', 'phalaenopsis', 'genus', 10),
  ('genus-phalaenopsis', 'Orchid', 'orchid', 'common', 10),
  ('genus-phalaenopsis', 'Phalaenopsis orchid', 'phalaenopsis orchid', 'common', 20),
  ('genus-phalaenopsis', 'Moth orchid', 'moth orchid', 'common', 20),
  ('genus-saintpaulia', 'Saintpaulia', 'saintpaulia', 'genus', 10),
  ('genus-saintpaulia', 'African violet', 'african violet', 'common', 10),
  ('genus-saintpaulia', 'Streptocarpus sect. Saintpaulia', 'streptocarpus sect saintpaulia', 'synonym', 20),
  ('species-hedera-helix', 'Hedera helix', 'hedera helix', 'scientific', 10),
  ('species-hedera-helix', 'English ivy', 'english ivy', 'common', 10),
  ('genus-philodendron', 'Philodendron', 'philodendron', 'genus', 10),
  ('genus-dracaena', 'Dracaena', 'dracaena', 'genus', 10),
  ('genus-peperomia', 'Peperomia', 'peperomia', 'genus', 10),
  ('genus-ficus', 'Ficus', 'ficus', 'genus', 10),
  ('genus-hoya', 'Hoya', 'hoya', 'genus', 10),
  ('care-group-succulent-like', 'Succulent', 'succulent', 'group', 10),
  ('care-group-succulent-like', 'Succulent-like', 'succulent like', 'group', 20),
  ('care-group-cactus', 'Cactus', 'cactus', 'group', 10),
  ('care-group-moderate-tropical', 'Tropical houseplant', 'tropical houseplant', 'group', 10),
  ('care-group-moisture-loving-tropical', 'Moisture-loving tropical', 'moisture loving tropical', 'group', 10),
  ('care-group-fern', 'Fern', 'fern', 'group', 10),
  ('care-group-orchid-bark', 'Orchid in bark', 'orchid in bark', 'group', 10),
  ('care-group-palm', 'Palm', 'palm', 'group', 10),
  ('fallback-unknown-conservative', 'Unknown houseplant', 'unknown houseplant', 'group', 10)
)
insert into public.care_profile_aliases (
  care_profile_id,
  alias,
  normalized_alias,
  alias_type,
  priority
)
select
  care_profiles.id,
  alias_seed.alias,
  alias_seed.normalized_alias,
  alias_seed.alias_type,
  alias_seed.priority
from alias_seed
join public.care_profiles
  on care_profiles.profile_key = alias_seed.profile_key
on conflict (care_profile_id, normalized_alias, alias_type) do update
set
  alias = excluded.alias,
  priority = excluded.priority;
