-- Generated from src/lib/care-profiles/fixtures.ts.
-- Regenerate with: node scripts/generate-care-profile-seed-sql.mjs

insert into public.care_profiles (
  profile_key,
  profile_level,
  display_name,
  accepted_scientific_name,
  accepted_common_name,
  taxon_rank,
  watering_interval_days_default,
  watering_interval_days_min,
  watering_interval_days_max,
  dryness_preference,
  watering_guidance,
  beginner_note,
  match_confidence,
  review_status,
  source_summary
)
values
  ('species-dracaena-trifasciata', 'species', 'Snake plant', 'Dracaena trifasciata', 'Snake plant', 'species', 21, 14, 28, 'dry_fully', 'Check when the soil has dried through most or all of the pot, then water thoroughly and drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-epipremnum-aureum', 'species', 'Pothos', 'Epipremnum aureum', 'Pothos', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil feels dry and the pot feels lighter.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-monstera-deliciosa', 'species', 'Monstera', 'Monstera deliciosa', 'Monstera', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two feels dry; water deeply and let extra water drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-spathiphyllum', 'genus', 'Peace lily', 'Spathiphyllum', 'Peace lily', 'genus', 7, 5, 10, 'lightly_moist', 'Check often and water when the surface starts to dry, before the plant wilts hard.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-zamioculcas-zamiifolia', 'species', 'ZZ plant', 'Zamioculcas zamiifolia', 'ZZ plant', 'species', 21, 14, 30, 'dry_fully', 'Check that the mix is fully dry before watering; this plant stores water and dislikes soggy soil.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-chlorophytum-comosum', 'species', 'Spider plant', 'Chlorophytum comosum', 'Spider plant', 'species', 7, 7, 14, 'dry_top_inch', 'Check weekly and water when the top inch feels dry.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-aloe-vera', 'species', 'Aloe vera', 'Aloe vera', 'Aloe vera', 'species', 21, 14, 30, 'dry_fully', 'Let the potting mix dry fully before watering again, then drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-crassula-ovata', 'species', 'Jade plant', 'Crassula ovata', 'Jade plant', 'species', 21, 14, 30, 'dry_fully', 'Check that the mix is dry before watering; thick leaves usually prefer a cautious cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-ficus-elastica', 'species', 'Rubber plant', 'Ficus elastica', 'Rubber plant', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil has dried; avoid leaving the pot in standing water.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-ficus-lyrata', 'species', 'Fiddle leaf fig', 'Ficus lyrata', 'Fiddle leaf fig', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil is dry; water evenly and let the pot drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-pilea-peperomioides', 'species', 'Chinese money plant', 'Pilea peperomioides', 'Chinese money plant', 'species', 7, 7, 10, 'dry_top_inch', 'Check when the top inch feels dry, then water and drain fully.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-nephrolepis-exaltata', 'species', 'Boston fern', 'Nephrolepis exaltata', 'Boston fern', 'species', 5, 3, 7, 'evenly_moist', 'Check every few days and keep the soil evenly moist, not soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-philodendron-hederaceum', 'species', 'Heartleaf philodendron', 'Philodendron hederaceum', 'Heartleaf philodendron', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil feels dry; this is a forgiving starter cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-phalaenopsis', 'genus', 'Moth orchid', 'Phalaenopsis', 'Orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the bark or moss mix; water when it is nearly dry, then let water drain completely.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-saintpaulia', 'genus', 'African violet', 'Saintpaulia', 'African violet', 'genus', 7, 5, 10, 'lightly_moist', 'Check when the surface starts to dry and water carefully without soaking the leaves.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-hedera-helix', 'species', 'English ivy', 'Hedera helix', 'English ivy', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; avoid letting the pot stay soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-dieffenbachia', 'genus', 'Dieffenbachia', 'Dieffenbachia', 'Dumb cane', 'genus', 7, 7, 14, 'dry_top_inch', 'Check when the top inch feels dry; water evenly and avoid letting the pot stay soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-aglaonema', 'genus', 'Aglaonema', 'Aglaonema', 'Aglaonema', 'genus', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two dries; keep the cadence moderate and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-chamaedorea-elegans', 'species', 'Parlor palm', 'Chamaedorea elegans', 'Parlor palm', 'species', 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries and water evenly through the pot.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-dypsis-lutescens', 'species', 'Areca palm', 'Dypsis lutescens', 'Areca palm', 'species', 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries; water thoroughly and let extra water drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-strelitzia-reginae', 'species', 'Bird of paradise', 'Strelitzia reginae', 'Bird of paradise', 'species', 10, 7, 14, 'dry_top_half', 'Check when the upper soil has dried; water deeply and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-curio-rowleyanus', 'species', 'String of pearls', 'Curio rowleyanus', 'String of pearls', 'species', 21, 14, 30, 'dry_fully', 'Let the potting mix dry fully before watering; pearls can rot if kept wet.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-calathea-goeppertia', 'genus', 'Calathea group', 'Goeppertia', 'Calathea', 'genus', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist, but avoid leaving the pot soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-maranta-leuconeura', 'species', 'Prayer plant', 'Maranta leuconeura', 'Red prayer plant', 'species', 5, 3, 7, 'lightly_moist', 'Check often and water when the surface starts to dry; avoid hard dry-downs.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-anthurium-andraeanum', 'species', 'Anthurium', 'Anthurium andraeanum', 'Anthurium', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and keep the mix airy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-codiaeum-variegatum', 'species', 'Croton', 'Codiaeum variegatum', 'Croton', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and avoid letting it sit dry too long.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-heptapleurum-schefflera', 'genus', 'Umbrella plant', 'Heptapleurum', 'Umbrella plant', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper soil has dried; water thoroughly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-tradescantia-zebrina', 'species', 'Tradescantia zebrina', 'Tradescantia zebrina', 'Wandering dude', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and avoid soggy soil.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-syngonium', 'genus', 'Syngonium', 'Syngonium', 'Arrowhead plant', 'genus', 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries; water evenly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-scindapsus-pictus', 'species', 'Satin pothos', 'Scindapsus pictus', 'Satin pothos', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix has dried; avoid keeping it soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-rhaphidophora-tetrasperma', 'species', 'Mini monstera', 'Rhaphidophora tetrasperma', 'Mini monstera', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two dries; water thoroughly and drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-dischidia', 'genus', 'Dischidia', 'Dischidia', 'Dischidia', 'genus', 14, 10, 21, 'dry_mostly', 'Check when most of the mix has dried; water lightly and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-begonia', 'genus', 'Begonia', 'Begonia', 'Begonia', 'genus', 7, 5, 10, 'dry_top_inch', 'Check when the surface starts to dry; keep evenly damp but not soggy.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-fittonia-albivenis', 'species', 'Nerve plant', 'Fittonia albivenis', 'Nerve plant', 'species', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist; avoid letting it dry hard.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-alocasia', 'genus', 'Alocasia', 'Alocasia', 'Alocasia', 'genus', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; keep the mix airy and avoid standing water.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-colocasia', 'genus', 'Colocasia', 'Colocasia', 'Colocasia', 'genus', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist, especially in bright warm conditions.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-haworthia', 'genus', 'Haworthia', 'Haworthia', 'Haworthia', 'genus', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; use a cautious succulent cadence.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-echeveria', 'genus', 'Echeveria', 'Echeveria', 'Echeveria', 'genus', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering and keep water out of the rosette.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-schlumbergera', 'genus', 'Holiday cactus', 'Schlumbergera', 'Holiday cactus', 'genus', 14, 10, 21, 'dry_top_half', 'Check when the upper mix dries; this cactus prefers less dry-down than desert cacti.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-beaucarnea-recurvata', 'species', 'Ponytail palm', 'Beaucarnea recurvata', 'Ponytail palm', 'species', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; the swollen base stores water.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-yucca', 'genus', 'Yucca', 'Yucca', 'Yucca', 'genus', 21, 14, 30, 'dry_fully', 'Check that most or all of the mix has dried before watering.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-aspidistra-elatior', 'species', 'Cast iron plant', 'Aspidistra elatior', 'Cast iron plant', 'species', 14, 10, 21, 'dry_mostly', 'Check when most of the mix has dried; this plant prefers a cautious cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-hypoestes-phyllostachya', 'species', 'Polka dot plant', 'Hypoestes phyllostachya', 'Polka dot plant', 'species', 5, 3, 7, 'lightly_moist', 'Check often and water when the surface starts to dry; avoid hard wilting.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-monstera-adansonii', 'species', 'Swiss cheese vine', 'Monstera adansonii', 'Swiss cheese vine', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two dries; water thoroughly and let extra water drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-epipremnum-pinnatum', 'species', 'Cebu blue pothos', 'Epipremnum pinnatum', 'Cebu blue pothos', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix has dried; water thoroughly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-scindapsus-treubii', 'species', 'Scindapsus treubii', 'Scindapsus treubii', 'Scindapsus treubii', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix has dried; avoid keeping the pot soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-philodendron-erubescens', 'species', 'Philodendron erubescens group', 'Philodendron erubescens', 'Philodendron erubescens group', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil has dried; water evenly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-philodendron-micans', 'species', 'Philodendron micans', 'Philodendron hederaceum var. hederaceum', 'Philodendron micans', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix dries; keep the cadence moderate and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-philodendron-gloriosum', 'species', 'Philodendron gloriosum', 'Philodendron gloriosum', 'Philodendron gloriosum', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two dries; water evenly and keep the mix airy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-thaumatophyllum-bipinnatifidum', 'species', 'Split-leaf philodendron', 'Thaumatophyllum bipinnatifidum', 'Split-leaf philodendron', 'species', 10, 7, 14, 'dry_top_half', 'Check when the upper soil has dried; water deeply and let extra water drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-thaumatophyllum-xanadu', 'species', 'Xanadu philodendron', 'Thaumatophyllum xanadu', 'Xanadu philodendron', 'species', 10, 7, 14, 'dry_top_half', 'Check when the upper soil has dried; water evenly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-anthurium-clarinervium', 'species', 'Velvet cardboard anthurium', 'Anthurium clarinervium', 'Velvet cardboard anthurium', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and keep the mix airy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-anthurium-crystallinum', 'species', 'Crystal anthurium', 'Anthurium crystallinum', 'Crystal anthurium', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and keep the mix airy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-homalomena', 'genus', 'Homalomena', 'Homalomena', 'Homalomena', 'genus', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and avoid standing water.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-amydrium', 'genus', 'Amydrium', 'Amydrium', 'Amydrium', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper mix has dried; water thoroughly and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-epipremnum-amplissimum', 'species', 'Epipremnum amplissimum', 'Epipremnum amplissimum', 'Epipremnum amplissimum', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix dries; water thoroughly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-rhaphidophora-decursiva', 'species', 'Rhaphidophora decursiva', 'Rhaphidophora decursiva', 'Rhaphidophora decursiva', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two dries; water thoroughly and drain.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-alocasia-amazonica', 'species', 'African mask alocasia', 'Alocasia x amazonica', 'African mask alocasia', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; keep the mix airy and avoid letting the pot sit wet.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-alocasia-reginula', 'species', 'Black velvet alocasia', 'Alocasia reginula', 'Black velvet alocasia', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water cautiously and keep the mix airy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-alocasia-zebrina', 'species', 'Alocasia zebrina', 'Alocasia zebrina', 'Alocasia zebrina', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-caladium', 'genus', 'Caladium', 'Caladium', 'Caladium', 'genus', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist while actively growing; avoid soggy soil.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-hoya-carnosa', 'species', 'Wax plant', 'Hoya carnosa', 'Wax plant', 'species', 14, 10, 21, 'dry_mostly', 'Check that most of the potting mix is dry before watering; drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-hoya-carnosa-compacta', 'species', 'Hindu rope hoya', 'Hoya carnosa compacta', 'Hindu rope hoya', 'species', 14, 10, 21, 'dry_mostly', 'Check that most of the mix is dry; water carefully through the dense vines and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-hoya-kerrii', 'species', 'Sweetheart hoya', 'Hoya kerrii', 'Sweetheart hoya', 'species', 14, 10, 21, 'dry_mostly', 'Check that most of the mix is dry before watering; small pots may dry faster.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-peperomia-obtusifolia', 'species', 'Baby rubber plant', 'Peperomia obtusifolia', 'Baby rubber plant', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix dries; water lightly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-peperomia-caperata', 'species', 'Ripple peperomia', 'Peperomia caperata', 'Ripple peperomia', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix dries; avoid letting the pot stay soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-peperomia-argyreia', 'species', 'Watermelon peperomia', 'Peperomia argyreia', 'Watermelon peperomia', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the mix dries; water lightly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-ceropegia-woodii', 'species', 'String of hearts', 'Ceropegia woodii', 'String of hearts', 'species', 14, 10, 21, 'dry_mostly', 'Check that most of the mix is dry before watering; avoid keeping the tubers wet.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-kalanchoe-blossfeldiana', 'species', 'Flaming Katy', 'Kalanchoe blossfeldiana', 'Flaming Katy', 'species', 14, 10, 21, 'dry_mostly', 'Check that most or all of the mix has dried before watering; drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-kalanchoe-tomentosa', 'species', 'Panda plant', 'Kalanchoe tomentosa', 'Panda plant', 'species', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; fuzzy succulent leaves dislike staying wet.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-sedum-morganianum', 'species', 'Burro''s tail', 'Sedum morganianum', 'Burro''s tail', 'species', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; water gently and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-portulacaria-afra', 'species', 'Elephant bush', 'Portulacaria afra', 'Elephant bush', 'species', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; use a cautious succulent cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-curio-herreanus', 'species', 'String of tears', 'Curio herreanus', 'String of tears', 'species', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; trailing beads can rot if kept wet.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-crassula-perforata', 'species', 'String of buttons', 'Crassula perforata', 'String of buttons', 'species', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; drain well and avoid frequent sips.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-aeonium', 'genus', 'Aeonium', 'Aeonium', 'Aeonium', 'genus', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; adjust slower during rest periods.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-lithops', 'genus', 'Lithops', 'Lithops', 'Lithops', 'genus', 35, 28, 45, 'dry_fully', 'Use a very cautious cadence and water only after the mix is fully dry.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-gasteria', 'genus', 'Gasteria', 'Gasteria', 'Gasteria', 'genus', 21, 14, 30, 'dry_fully', 'Let the mix dry fully before watering; drain well and avoid standing water.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-asplenium-nidus', 'species', 'Bird''s nest fern', 'Asplenium nidus', 'Bird''s nest fern', 'species', 5, 3, 7, 'evenly_moist', 'Check every few days and keep evenly moist, but avoid water sitting in the crown.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-adiantum', 'genus', 'Maidenhair fern', 'Maidenhair fern', 'Maidenhair fern', 'genus', 3, 2, 5, 'evenly_moist', 'Check very often and keep evenly moist; avoid letting the pot dry hard.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-pteris', 'genus', 'Brake fern', 'Brake fern', 'Brake fern', 'genus', 5, 3, 7, 'evenly_moist', 'Check often and keep evenly moist with good drainage.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-platycerium', 'genus', 'Staghorn fern', 'Staghorn fern', 'Staghorn fern', 'genus', 7, 5, 10, 'special_medium', 'Check the mount or loose mix; water when it is starting to dry but not bone dry.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-selaginella', 'genus', 'Selaginella', 'Selaginella', 'Selaginella', 'genus', 3, 2, 5, 'evenly_moist', 'Check very often and keep evenly moist; this plant declines after hard dry-downs.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-soleirolia-soleirolii', 'species', 'Baby''s tears', 'Soleirolia soleirolii', 'Baby''s tears', 'species', 3, 2, 5, 'evenly_moist', 'Check very often and keep evenly moist; small pots can dry quickly.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-howea-forsteriana', 'species', 'Kentia palm', 'Howea forsteriana', 'Kentia palm', 'species', 10, 7, 14, 'dry_top_inch', 'Check when the top inch or two dries; water evenly through the pot.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-rhapis-excelsa', 'species', 'Lady palm', 'Rhapis excelsa', 'Lady palm', 'species', 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries; water evenly and avoid soggy soil.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-caryota-mitis', 'species', 'Fishtail palm', 'Caryota mitis', 'Fishtail palm', 'species', 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries; water evenly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-dracaena-fragrans', 'species', 'Corn plant', 'Dracaena fragrans', 'Corn plant', 'species', 14, 10, 21, 'dry_mostly', 'Check when most of the soil has dried; water thoroughly and drain, and avoid keeping the cane or roots soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-dracaena-marginata', 'species', 'Dragon tree', 'Dracaena marginata', 'Dragon tree', 'species', 14, 10, 21, 'dry_mostly', 'Check when most of the soil has dried; this plant prefers a cautious cadence.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-dracaena-reflexa', 'species', 'Song of India', 'Dracaena reflexa', 'Song of India', 'species', 14, 10, 21, 'dry_mostly', 'Check when most of the soil has dried; avoid keeping roots constantly wet.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-cordyline-fruticosa', 'species', 'Ti plant', 'Cordyline fruticosa', 'Ti plant', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and avoid hard dry-downs.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-aeschynanthus', 'genus', 'Lipstick plant', 'Lipstick plant', 'Lipstick plant', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper mix has dried; water thoroughly and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-nematanthus', 'genus', 'Goldfish plant', 'Goldfish plant', 'Goldfish plant', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper mix has dried; water evenly and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-columnea', 'genus', 'Columnea', 'Columnea', 'Columnea', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper mix has dried; water evenly and avoid soggy soil.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-oxalis-triangularis', 'species', 'Purple shamrock', 'Oxalis triangularis', 'Purple shamrock', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly, and pause if the plant goes dormant.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-cyclamen-persicum', 'species', 'Florist''s cyclamen', 'Cyclamen persicum', 'Florist''s cyclamen', 'species', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist while actively growing; avoid soaking the crown.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-begonia-maculata', 'species', 'Polka dot begonia', 'Begonia maculata', 'Polka dot begonia', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the surface starts to dry; keep evenly damp but not soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-dionaea-muscipula', 'species', 'Venus flytrap', 'Dionaea muscipula', 'Venus flytrap', 'species', 3, 2, 5, 'special_medium', 'Keep the special medium consistently wet with mineral-free water; do not let it dry out.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-dendrobium', 'genus', 'Dendrobium orchid', 'Dendrobium orchid', 'Dendrobium orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the bark or moss mix; water when the medium is close to dry, then drain completely.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-oncidium', 'genus', 'Oncidium orchid', 'Oncidium orchid', 'Oncidium orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the bark or moss mix; water when it is starting to dry, then drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-cattleya', 'genus', 'Cattleya orchid', 'Cattleya orchid', 'Cattleya orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the bark or coarse mix; water when it is nearly dry, then drain completely.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-paphiopedilum', 'genus', 'Paphiopedilum orchid', 'Paphiopedilum orchid', 'Paphiopedilum orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the orchid mix often and water when it is just starting to dry; drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-cymbidium', 'genus', 'Cymbidium orchid', 'Cymbidium orchid', 'Cymbidium orchid', 'genus', 7, 5, 10, 'special_medium', 'Check the orchid mix and water when it is starting to dry; let extra water drain.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-pachira-aquatica', 'species', 'Money tree', 'Pachira aquatica', 'Money tree', 'species', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil has dried; water thoroughly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-dracaena-sanderiana', 'species', 'Lucky bamboo', 'Dracaena sanderiana', 'Lucky bamboo', 'species', 7, 5, 10, 'special_medium', 'Check the water or potting medium often; keep roots lightly moist without stagnant water.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-araucaria-heterophylla', 'species', 'Norfolk Island pine', 'Araucaria heterophylla', 'Norfolk Island pine', 'species', 7, 5, 10, 'lightly_moist', 'Check when the surface starts to dry; keep lightly moist but not soggy.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-stromanthe-thalia', 'species', 'Triostar stromanthe', 'Stromanthe thalia', 'Triostar stromanthe', 'species', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist; avoid hard dry-downs and standing water.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-ctenanthe', 'genus', 'Ctenanthe', 'Ctenanthe', 'Ctenanthe', 'genus', 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist, but do not leave the pot soggy.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-polyscias-fruticosa', 'species', 'Ming aralia', 'Polyscias fruticosa', 'Ming aralia', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and avoid soggy soil.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('species-plerandra-elegantissima', 'species', 'False aralia', 'Plerandra elegantissima', 'False aralia', 'species', 7, 5, 10, 'dry_top_inch', 'Check when the top inch dries; water evenly and drain well.', 'Common houseplant starter profile for editable watering setup.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-nepenthes', 'genus', 'Tropical pitcher plant', 'Tropical pitcher plant', 'Tropical pitcher plant', 'genus', 5, 3, 7, 'special_medium', 'Keep the special medium lightly moist with mineral-free water; drain rather than leave waterlogged.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-philodendron', 'genus', 'Philodendron', 'Philodendron', 'Philodendron', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the top half of the soil has dried; avoid soggy soil.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-dracaena', 'genus', 'Dracaena', 'Dracaena', 'Dracaena', 'genus', 14, 10, 21, 'dry_mostly', 'Check when most of the soil has dried; many dracaenas prefer a cautious cadence.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-peperomia', 'genus', 'Peperomia', 'Peperomia', 'Peperomia', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the top half is dry; water lightly and drain well.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-ficus', 'genus', 'Ficus', 'Ficus', 'Ficus', 'genus', 10, 7, 14, 'dry_top_half', 'Check when the upper soil has dried; keep the cadence steady and avoid soggy roots.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('genus-hoya', 'genus', 'Hoya', 'Hoya', 'Hoya', 'genus', 14, 10, 21, 'dry_mostly', 'Check that most of the potting mix is dry before watering.', 'Genus-level starter for cases where exact species is uncertain.', 'medium', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-succulent-like', 'care_group', 'Succulent-like houseplant', null, 'Succulent-like houseplant', null, 21, 14, 30, 'dry_fully', 'Start cautiously: check that the mix is fully dry before watering.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-cactus', 'care_group', 'Cactus / very dry houseplant', null, 'Cactus / very dry houseplant', null, 28, 21, 35, 'dry_fully', 'Check infrequently and water only after the mix has fully dried.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-moderate-tropical', 'care_group', 'Moderate tropical houseplant', null, 'Moderate tropical houseplant', null, 7, 7, 14, 'dry_top_inch', 'Start by checking weekly and water when the top inch feels dry.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-moisture-loving-tropical', 'care_group', 'Moisture-loving tropical houseplant', null, 'Moisture-loving tropical houseplant', null, 5, 3, 7, 'lightly_moist', 'Check often and keep lightly moist, but do not leave the pot soggy.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-fern', 'care_group', 'Fern / evenly moist houseplant', null, 'Fern / evenly moist houseplant', null, 5, 3, 7, 'evenly_moist', 'Check often and keep evenly moist with good drainage.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-orchid-bark', 'care_group', 'Orchid in bark mix', null, 'Orchid in bark mix', null, 7, 5, 10, 'special_medium', 'Check the bark mix and water when it is nearly dry, then drain completely.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('care-group-palm', 'care_group', 'Palm houseplant', null, 'Palm houseplant', null, 7, 7, 14, 'dry_top_inch', 'Check when the top inch dries and water evenly through the pot.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.'),
  ('fallback-unknown-conservative', 'fallback', 'Unknown conservative starter', null, 'Unknown conservative starter', null, 7, 5, 10, 'unknown_conservative', 'Start by checking every week and water only when the top inch feels dry; adjust after you learn the plant.', 'Care-group starter for conservative setup when identity is broad or uncertain.', 'low', 'needs_review', 'Wave 1/2 conservative starter profile compiled for Plant Care setup; concise copy should be reviewed during user-facing QA.')
on conflict (profile_key) do update
set
  profile_level = excluded.profile_level,
  display_name = excluded.display_name,
  accepted_scientific_name = excluded.accepted_scientific_name,
  accepted_common_name = excluded.accepted_common_name,
  taxon_rank = excluded.taxon_rank,
  watering_interval_days_default = excluded.watering_interval_days_default,
  watering_interval_days_min = excluded.watering_interval_days_min,
  watering_interval_days_max = excluded.watering_interval_days_max,
  dryness_preference = excluded.dryness_preference,
  watering_guidance = excluded.watering_guidance,
  beginner_note = excluded.beginner_note,
  match_confidence = excluded.match_confidence,
  review_status = excluded.review_status,
  source_summary = excluded.source_summary;

with alias_seed(profile_key, alias, normalized_alias, alias_type, priority) as (
  values
  ('species-dracaena-trifasciata', 'Dracaena trifasciata', 'dracaena trifasciata', 'scientific', 10),
  ('species-dracaena-trifasciata', 'Snake plant', 'snake plant', 'common', 10),
  ('species-dracaena-trifasciata', 'Sansevieria trifasciata', 'sansevieria trifasciata', 'synonym', 20),
  ('species-dracaena-trifasciata', 'Mother-in-law''s tongue', 'mother in laws tongue', 'common', 30),
  ('species-epipremnum-aureum', 'Epipremnum aureum', 'epipremnum aureum', 'scientific', 10),
  ('species-epipremnum-aureum', 'Pothos', 'pothos', 'common', 10),
  ('species-epipremnum-aureum', 'Devil''s ivy', 'devils ivy', 'common', 20),
  ('species-epipremnum-aureum', 'Golden pothos', 'golden pothos', 'common', 20),
  ('species-epipremnum-aureum', 'Money plant', 'money plant', 'common', 90),
  ('species-monstera-deliciosa', 'Monstera deliciosa', 'monstera deliciosa', 'scientific', 10),
  ('species-monstera-deliciosa', 'Monstera', 'monstera', 'common', 10),
  ('species-monstera-deliciosa', 'Swiss cheese plant', 'swiss cheese plant', 'common', 20),
  ('genus-spathiphyllum', 'Spathiphyllum', 'spathiphyllum', 'genus', 10),
  ('genus-spathiphyllum', 'Peace lily', 'peace lily', 'common', 10),
  ('species-zamioculcas-zamiifolia', 'Zamioculcas zamiifolia', 'zamioculcas zamiifolia', 'scientific', 10),
  ('species-zamioculcas-zamiifolia', 'ZZ plant', 'zz plant', 'common', 10),
  ('species-zamioculcas-zamiifolia', 'Zanzibar gem', 'zanzibar gem', 'common', 20),
  ('species-chlorophytum-comosum', 'Chlorophytum comosum', 'chlorophytum comosum', 'scientific', 10),
  ('species-chlorophytum-comosum', 'Spider plant', 'spider plant', 'common', 10),
  ('species-chlorophytum-comosum', 'Airplane plant', 'airplane plant', 'common', 20),
  ('species-chlorophytum-comosum', 'Ribbon plant', 'ribbon plant', 'common', 20),
  ('species-chlorophytum-comosum', 'Spider ivy', 'spider ivy', 'common', 30),
  ('species-chlorophytum-comosum', 'Variegated spider plant', 'variegated spider plant', 'common', 30),
  ('species-chlorophytum-comosum', 'Bonnie spider plant', 'bonnie spider plant', 'common', 30),
  ('species-chlorophytum-comosum', 'Chlorophytum comosum ''Vittatum''', 'chlorophytum comosum vittatum', 'synonym', 30),
  ('species-chlorophytum-comosum', 'Chlorophytum comosum ''Variegatum''', 'chlorophytum comosum variegatum', 'synonym', 30),
  ('species-aloe-vera', 'Aloe vera', 'aloe vera', 'scientific', 10),
  ('species-aloe-vera', 'Aloe vera', 'aloe vera', 'common', 10),
  ('species-aloe-vera', 'Aloe', 'aloe', 'common', 20),
  ('species-crassula-ovata', 'Crassula ovata', 'crassula ovata', 'scientific', 10),
  ('species-crassula-ovata', 'Jade plant', 'jade plant', 'common', 10),
  ('species-ficus-elastica', 'Ficus elastica', 'ficus elastica', 'scientific', 10),
  ('species-ficus-elastica', 'Rubber plant', 'rubber plant', 'common', 10),
  ('species-ficus-elastica', 'Rubber tree', 'rubber tree', 'common', 20),
  ('species-ficus-lyrata', 'Ficus lyrata', 'ficus lyrata', 'scientific', 10),
  ('species-ficus-lyrata', 'Fiddle leaf fig', 'fiddle leaf fig', 'common', 10),
  ('species-pilea-peperomioides', 'Pilea peperomioides', 'pilea peperomioides', 'scientific', 10),
  ('species-pilea-peperomioides', 'Chinese money plant', 'chinese money plant', 'common', 10),
  ('species-pilea-peperomioides', 'Money plant', 'money plant', 'common', 90),
  ('species-pilea-peperomioides', 'Pancake plant', 'pancake plant', 'common', 20),
  ('species-nephrolepis-exaltata', 'Nephrolepis exaltata', 'nephrolepis exaltata', 'scientific', 10),
  ('species-nephrolepis-exaltata', 'Boston fern', 'boston fern', 'common', 10),
  ('species-philodendron-hederaceum', 'Philodendron hederaceum', 'philodendron hederaceum', 'scientific', 10),
  ('species-philodendron-hederaceum', 'Heartleaf philodendron', 'heartleaf philodendron', 'common', 10),
  ('genus-phalaenopsis', 'Phalaenopsis', 'phalaenopsis', 'genus', 10),
  ('genus-phalaenopsis', 'Orchid', 'orchid', 'common', 10),
  ('genus-phalaenopsis', 'Phalaenopsis orchid', 'phalaenopsis orchid', 'common', 20),
  ('genus-phalaenopsis', 'Moth orchid', 'moth orchid', 'common', 20),
  ('genus-phalaenopsis', 'Phalaenopsis', 'phalaenopsis', 'common', 20),
  ('genus-phalaenopsis', 'Grocery store orchid', 'grocery store orchid', 'common', 30),
  ('genus-phalaenopsis', 'Supermarket orchid', 'supermarket orchid', 'common', 30),
  ('genus-saintpaulia', 'Saintpaulia', 'saintpaulia', 'genus', 10),
  ('genus-saintpaulia', 'African violet', 'african violet', 'common', 10),
  ('genus-saintpaulia', 'Streptocarpus sect. Saintpaulia', 'streptocarpus sect saintpaulia', 'synonym', 20),
  ('species-hedera-helix', 'Hedera helix', 'hedera helix', 'scientific', 10),
  ('species-hedera-helix', 'English ivy', 'english ivy', 'common', 10),
  ('genus-dieffenbachia', 'Dieffenbachia', 'dieffenbachia', 'genus', 10),
  ('genus-dieffenbachia', 'Dumb cane', 'dumb cane', 'common', 10),
  ('genus-dieffenbachia', 'Dieffenbachia', 'dieffenbachia', 'common', 10),
  ('genus-aglaonema', 'Aglaonema', 'aglaonema', 'genus', 10),
  ('genus-aglaonema', 'Chinese evergreen', 'chinese evergreen', 'common', 10),
  ('species-chamaedorea-elegans', 'Chamaedorea elegans', 'chamaedorea elegans', 'scientific', 10),
  ('species-chamaedorea-elegans', 'Parlor palm', 'parlor palm', 'common', 10),
  ('species-chamaedorea-elegans', 'Neanthe bella palm', 'neanthe bella palm', 'common', 30),
  ('species-dypsis-lutescens', 'Dypsis lutescens', 'dypsis lutescens', 'scientific', 10),
  ('species-dypsis-lutescens', 'Areca palm', 'areca palm', 'common', 10),
  ('species-dypsis-lutescens', 'Butterfly palm', 'butterfly palm', 'common', 20),
  ('species-dypsis-lutescens', 'Golden cane palm', 'golden cane palm', 'common', 30),
  ('species-strelitzia-reginae', 'Strelitzia reginae', 'strelitzia reginae', 'scientific', 10),
  ('species-strelitzia-reginae', 'Bird of paradise', 'bird of paradise', 'common', 10),
  ('species-strelitzia-reginae', 'Orange bird of paradise', 'orange bird of paradise', 'common', 30),
  ('species-curio-rowleyanus', 'Curio rowleyanus', 'curio rowleyanus', 'scientific', 10),
  ('species-curio-rowleyanus', 'String of pearls', 'string of pearls', 'common', 10),
  ('species-curio-rowleyanus', 'Senecio rowleyanus', 'senecio rowleyanus', 'synonym', 20),
  ('species-curio-rowleyanus', 'Pearl plant', 'pearl plant', 'common', 30),
  ('genus-calathea-goeppertia', 'Goeppertia', 'goeppertia', 'genus', 10),
  ('genus-calathea-goeppertia', 'Calathea', 'calathea', 'common', 10),
  ('genus-calathea-goeppertia', 'Calathea', 'calathea', 'genus', 10),
  ('genus-calathea-goeppertia', 'Prayer plant', 'prayer plant', 'common', 80),
  ('species-maranta-leuconeura', 'Maranta leuconeura', 'maranta leuconeura', 'scientific', 10),
  ('species-maranta-leuconeura', 'Red prayer plant', 'red prayer plant', 'common', 10),
  ('species-maranta-leuconeura', 'Red prayer plant', 'red prayer plant', 'common', 30),
  ('species-maranta-leuconeura', 'Prayer plant', 'prayer plant', 'common', 80),
  ('species-anthurium-andraeanum', 'Anthurium andraeanum', 'anthurium andraeanum', 'scientific', 10),
  ('species-anthurium-andraeanum', 'Anthurium', 'anthurium', 'common', 10),
  ('species-anthurium-andraeanum', 'Flamingo flower', 'flamingo flower', 'common', 20),
  ('species-codiaeum-variegatum', 'Codiaeum variegatum', 'codiaeum variegatum', 'scientific', 10),
  ('species-codiaeum-variegatum', 'Croton', 'croton', 'common', 10),
  ('species-codiaeum-variegatum', 'Garden croton', 'garden croton', 'common', 20),
  ('genus-heptapleurum-schefflera', 'Heptapleurum', 'heptapleurum', 'genus', 10),
  ('genus-heptapleurum-schefflera', 'Umbrella plant', 'umbrella plant', 'common', 10),
  ('genus-heptapleurum-schefflera', 'Schefflera', 'schefflera', 'synonym', 20),
  ('genus-heptapleurum-schefflera', 'Dwarf umbrella tree', 'dwarf umbrella tree', 'common', 30),
  ('species-tradescantia-zebrina', 'Tradescantia zebrina', 'tradescantia zebrina', 'scientific', 10),
  ('species-tradescantia-zebrina', 'Wandering dude', 'wandering dude', 'common', 10),
  ('species-tradescantia-zebrina', 'Inch plant', 'inch plant', 'common', 20),
  ('species-tradescantia-zebrina', 'Wandering plant', 'wandering plant', 'common', 30),
  ('genus-syngonium', 'Syngonium', 'syngonium', 'genus', 10),
  ('genus-syngonium', 'Arrowhead plant', 'arrowhead plant', 'common', 10),
  ('genus-syngonium', 'Arrowhead vine', 'arrowhead vine', 'common', 20),
  ('genus-syngonium', 'Nephthytis', 'nephthytis', 'synonym', 40),
  ('species-scindapsus-pictus', 'Scindapsus pictus', 'scindapsus pictus', 'scientific', 10),
  ('species-scindapsus-pictus', 'Satin pothos', 'satin pothos', 'common', 10),
  ('species-scindapsus-pictus', 'Silver pothos', 'silver pothos', 'common', 20),
  ('species-scindapsus-pictus', 'Silver satin pothos', 'silver satin pothos', 'common', 30),
  ('species-rhaphidophora-tetrasperma', 'Rhaphidophora tetrasperma', 'rhaphidophora tetrasperma', 'scientific', 10),
  ('species-rhaphidophora-tetrasperma', 'Mini monstera', 'mini monstera', 'common', 10),
  ('species-rhaphidophora-tetrasperma', 'Monstera minima', 'monstera minima', 'common', 30),
  ('genus-dischidia', 'Dischidia', 'dischidia', 'genus', 10),
  ('genus-dischidia', 'String of nickels', 'string of nickels', 'common', 20),
  ('genus-begonia', 'Begonia', 'begonia', 'genus', 10),
  ('genus-begonia', 'Rex begonia', 'rex begonia', 'common', 20),
  ('genus-begonia', 'Angel wing begonia', 'angel wing begonia', 'common', 80),
  ('species-fittonia-albivenis', 'Fittonia albivenis', 'fittonia albivenis', 'scientific', 10),
  ('species-fittonia-albivenis', 'Nerve plant', 'nerve plant', 'common', 10),
  ('species-fittonia-albivenis', 'Fittonia', 'fittonia', 'common', 20),
  ('genus-alocasia', 'Alocasia', 'alocasia', 'genus', 10),
  ('genus-alocasia', 'Elephant ear', 'elephant ear', 'common', 40),
  ('genus-colocasia', 'Colocasia', 'colocasia', 'genus', 10),
  ('genus-colocasia', 'Elephant ear', 'elephant ear', 'common', 40),
  ('genus-colocasia', 'Taro', 'taro', 'common', 30),
  ('genus-haworthia', 'Haworthia', 'haworthia', 'genus', 10),
  ('genus-haworthia', 'Zebra haworthia', 'zebra haworthia', 'common', 20),
  ('genus-haworthia', 'Zebra plant', 'zebra plant', 'common', 80),
  ('genus-echeveria', 'Echeveria', 'echeveria', 'genus', 10),
  ('genus-echeveria', 'Hen and chicks', 'hen and chicks', 'common', 50),
  ('genus-schlumbergera', 'Schlumbergera', 'schlumbergera', 'genus', 10),
  ('genus-schlumbergera', 'Holiday cactus', 'holiday cactus', 'common', 10),
  ('genus-schlumbergera', 'Christmas cactus', 'christmas cactus', 'common', 20),
  ('genus-schlumbergera', 'Thanksgiving cactus', 'thanksgiving cactus', 'common', 20),
  ('species-beaucarnea-recurvata', 'Beaucarnea recurvata', 'beaucarnea recurvata', 'scientific', 10),
  ('species-beaucarnea-recurvata', 'Ponytail palm', 'ponytail palm', 'common', 10),
  ('species-beaucarnea-recurvata', 'Elephant foot plant', 'elephant foot plant', 'common', 30),
  ('genus-yucca', 'Yucca', 'yucca', 'genus', 10),
  ('genus-yucca', 'Yucca cane', 'yucca cane', 'common', 20),
  ('genus-yucca', 'Spineless yucca', 'spineless yucca', 'common', 30),
  ('species-aspidistra-elatior', 'Aspidistra elatior', 'aspidistra elatior', 'scientific', 10),
  ('species-aspidistra-elatior', 'Cast iron plant', 'cast iron plant', 'common', 10),
  ('species-aspidistra-elatior', 'Bar room plant', 'bar room plant', 'common', 30),
  ('species-hypoestes-phyllostachya', 'Hypoestes phyllostachya', 'hypoestes phyllostachya', 'scientific', 10),
  ('species-hypoestes-phyllostachya', 'Polka dot plant', 'polka dot plant', 'common', 10),
  ('species-hypoestes-phyllostachya', 'Freckle face plant', 'freckle face plant', 'common', 30),
  ('species-monstera-adansonii', 'Monstera adansonii', 'monstera adansonii', 'scientific', 10),
  ('species-monstera-adansonii', 'Swiss cheese vine', 'swiss cheese vine', 'common', 10),
  ('species-monstera-adansonii', 'Adanson''s monstera', 'adansons monstera', 'common', 20),
  ('species-monstera-adansonii', 'Monstera friedrichsthalii', 'monstera friedrichsthalii', 'synonym', 30),
  ('species-epipremnum-pinnatum', 'Epipremnum pinnatum', 'epipremnum pinnatum', 'scientific', 10),
  ('species-epipremnum-pinnatum', 'Cebu blue pothos', 'cebu blue pothos', 'common', 10),
  ('species-epipremnum-pinnatum', 'Dragon tail pothos', 'dragon tail pothos', 'common', 30),
  ('species-epipremnum-pinnatum', 'Blue pothos', 'blue pothos', 'common', 30),
  ('species-scindapsus-treubii', 'Scindapsus treubii', 'scindapsus treubii', 'scientific', 10),
  ('species-scindapsus-treubii', 'Scindapsus treubii', 'scindapsus treubii', 'common', 10),
  ('species-scindapsus-treubii', 'Moonlight scindapsus', 'moonlight scindapsus', 'common', 20),
  ('species-scindapsus-treubii', 'Scindapsus treubii Moonlight', 'scindapsus treubii moonlight', 'common', 30),
  ('species-scindapsus-treubii', 'Dark form scindapsus', 'dark form scindapsus', 'common', 30),
  ('species-philodendron-erubescens', 'Philodendron erubescens', 'philodendron erubescens', 'scientific', 10),
  ('species-philodendron-erubescens', 'Philodendron erubescens group', 'philodendron erubescens group', 'common', 10),
  ('species-philodendron-erubescens', 'Pink princess philodendron', 'pink princess philodendron', 'common', 20),
  ('species-philodendron-erubescens', 'Imperial red philodendron', 'imperial red philodendron', 'common', 20),
  ('species-philodendron-erubescens', 'Rojo congo philodendron', 'rojo congo philodendron', 'common', 20),
  ('species-philodendron-erubescens', 'Blushing philodendron', 'blushing philodendron', 'common', 30),
  ('species-philodendron-micans', 'Philodendron hederaceum var. hederaceum', 'philodendron hederaceum var hederaceum', 'scientific', 10),
  ('species-philodendron-micans', 'Philodendron micans', 'philodendron micans', 'common', 10),
  ('species-philodendron-micans', 'Philodendron micans', 'philodendron micans', 'synonym', 20),
  ('species-philodendron-micans', 'Velvet leaf philodendron', 'velvet leaf philodendron', 'common', 20),
  ('species-philodendron-micans', 'Velvet philodendron', 'velvet philodendron', 'common', 30),
  ('species-philodendron-gloriosum', 'Philodendron gloriosum', 'philodendron gloriosum', 'scientific', 10),
  ('species-philodendron-gloriosum', 'Philodendron gloriosum', 'philodendron gloriosum', 'common', 10),
  ('species-philodendron-gloriosum', 'Gloriosum philodendron', 'gloriosum philodendron', 'common', 20),
  ('species-thaumatophyllum-bipinnatifidum', 'Thaumatophyllum bipinnatifidum', 'thaumatophyllum bipinnatifidum', 'scientific', 10),
  ('species-thaumatophyllum-bipinnatifidum', 'Split-leaf philodendron', 'split leaf philodendron', 'common', 10),
  ('species-thaumatophyllum-bipinnatifidum', 'Philodendron bipinnatifidum', 'philodendron bipinnatifidum', 'synonym', 20),
  ('species-thaumatophyllum-bipinnatifidum', 'Tree philodendron', 'tree philodendron', 'common', 20),
  ('species-thaumatophyllum-bipinnatifidum', 'Lacy tree philodendron', 'lacy tree philodendron', 'common', 30),
  ('species-thaumatophyllum-xanadu', 'Thaumatophyllum xanadu', 'thaumatophyllum xanadu', 'scientific', 10),
  ('species-thaumatophyllum-xanadu', 'Xanadu philodendron', 'xanadu philodendron', 'common', 10),
  ('species-thaumatophyllum-xanadu', 'Philodendron xanadu', 'philodendron xanadu', 'synonym', 20),
  ('species-thaumatophyllum-xanadu', 'Xanadu', 'xanadu', 'common', 20),
  ('species-anthurium-clarinervium', 'Anthurium clarinervium', 'anthurium clarinervium', 'scientific', 10),
  ('species-anthurium-clarinervium', 'Velvet cardboard anthurium', 'velvet cardboard anthurium', 'common', 10),
  ('species-anthurium-clarinervium', 'Anthurium clarinervium', 'anthurium clarinervium', 'common', 20),
  ('species-anthurium-crystallinum', 'Anthurium crystallinum', 'anthurium crystallinum', 'scientific', 10),
  ('species-anthurium-crystallinum', 'Crystal anthurium', 'crystal anthurium', 'common', 10),
  ('species-anthurium-crystallinum', 'Anthurium crystallinum', 'anthurium crystallinum', 'common', 20),
  ('genus-homalomena', 'Homalomena', 'homalomena', 'genus', 10),
  ('genus-homalomena', 'Queen of hearts plant', 'queen of hearts plant', 'common', 30),
  ('genus-homalomena', 'Emerald gem plant', 'emerald gem plant', 'common', 30),
  ('genus-amydrium', 'Amydrium', 'amydrium', 'genus', 10),
  ('genus-amydrium', 'Spiderman monstera', 'spiderman monstera', 'common', 30),
  ('species-epipremnum-amplissimum', 'Epipremnum amplissimum', 'epipremnum amplissimum', 'scientific', 10),
  ('species-epipremnum-amplissimum', 'Epipremnum amplissimum', 'epipremnum amplissimum', 'common', 10),
  ('species-epipremnum-amplissimum', 'Silver streak pothos', 'silver streak pothos', 'common', 30),
  ('species-rhaphidophora-decursiva', 'Rhaphidophora decursiva', 'rhaphidophora decursiva', 'scientific', 10),
  ('species-rhaphidophora-decursiva', 'Rhaphidophora decursiva', 'rhaphidophora decursiva', 'common', 10),
  ('species-rhaphidophora-decursiva', 'Dragon tail plant', 'dragon tail plant', 'common', 30),
  ('species-rhaphidophora-decursiva', 'Creeping philodendron', 'creeping philodendron', 'common', 40),
  ('species-alocasia-amazonica', 'Alocasia x amazonica', 'alocasia x amazonica', 'scientific', 10),
  ('species-alocasia-amazonica', 'African mask alocasia', 'african mask alocasia', 'common', 10),
  ('species-alocasia-amazonica', 'Alocasia amazonica', 'alocasia amazonica', 'synonym', 20),
  ('species-alocasia-amazonica', 'African mask plant', 'african mask plant', 'common', 20),
  ('species-alocasia-amazonica', 'Alocasia Polly', 'alocasia polly', 'common', 30),
  ('species-alocasia-reginula', 'Alocasia reginula', 'alocasia reginula', 'scientific', 10),
  ('species-alocasia-reginula', 'Black velvet alocasia', 'black velvet alocasia', 'common', 10),
  ('species-alocasia-reginula', 'Black velvet', 'black velvet', 'common', 30),
  ('species-alocasia-zebrina', 'Alocasia zebrina', 'alocasia zebrina', 'scientific', 10),
  ('species-alocasia-zebrina', 'Alocasia zebrina', 'alocasia zebrina', 'common', 10),
  ('species-alocasia-zebrina', 'Zebra alocasia', 'zebra alocasia', 'common', 20),
  ('species-alocasia-zebrina', 'Zebra plant', 'zebra plant', 'common', 80),
  ('genus-caladium', 'Caladium', 'caladium', 'genus', 10),
  ('genus-caladium', 'Angel wings', 'angel wings', 'common', 30),
  ('genus-caladium', 'Heart of Jesus', 'heart of jesus', 'common', 30),
  ('genus-caladium', 'Elephant ear', 'elephant ear', 'common', 40),
  ('species-hoya-carnosa', 'Hoya carnosa', 'hoya carnosa', 'scientific', 10),
  ('species-hoya-carnosa', 'Wax plant', 'wax plant', 'common', 10),
  ('species-hoya-carnosa', 'Hoya carnosa', 'hoya carnosa', 'common', 20),
  ('species-hoya-carnosa', 'Porcelain flower', 'porcelain flower', 'common', 30),
  ('species-hoya-carnosa', 'Krimson queen hoya', 'krimson queen hoya', 'common', 40),
  ('species-hoya-carnosa', 'Krimson princess hoya', 'krimson princess hoya', 'common', 40),
  ('species-hoya-carnosa-compacta', 'Hoya carnosa compacta', 'hoya carnosa compacta', 'scientific', 10),
  ('species-hoya-carnosa-compacta', 'Hindu rope hoya', 'hindu rope hoya', 'common', 10),
  ('species-hoya-carnosa-compacta', 'Hoya compacta', 'hoya compacta', 'synonym', 20),
  ('species-hoya-carnosa-compacta', 'Hindu rope plant', 'hindu rope plant', 'common', 20),
  ('species-hoya-carnosa-compacta', 'Rope hoya', 'rope hoya', 'common', 30),
  ('species-hoya-kerrii', 'Hoya kerrii', 'hoya kerrii', 'scientific', 10),
  ('species-hoya-kerrii', 'Sweetheart hoya', 'sweetheart hoya', 'common', 10),
  ('species-hoya-kerrii', 'Heart hoya', 'heart hoya', 'common', 20),
  ('species-hoya-kerrii', 'Valentine hoya', 'valentine hoya', 'common', 30),
  ('species-hoya-kerrii', 'Lucky heart plant', 'lucky heart plant', 'common', 30),
  ('species-peperomia-obtusifolia', 'Peperomia obtusifolia', 'peperomia obtusifolia', 'scientific', 10),
  ('species-peperomia-obtusifolia', 'Baby rubber plant', 'baby rubber plant', 'common', 10),
  ('species-peperomia-obtusifolia', 'Pepper face', 'pepper face', 'common', 30),
  ('species-peperomia-obtusifolia', 'American rubber plant', 'american rubber plant', 'common', 30),
  ('species-peperomia-caperata', 'Peperomia caperata', 'peperomia caperata', 'scientific', 10),
  ('species-peperomia-caperata', 'Ripple peperomia', 'ripple peperomia', 'common', 10),
  ('species-peperomia-caperata', 'Emerald ripple peperomia', 'emerald ripple peperomia', 'common', 20),
  ('species-peperomia-argyreia', 'Peperomia argyreia', 'peperomia argyreia', 'scientific', 10),
  ('species-peperomia-argyreia', 'Watermelon peperomia', 'watermelon peperomia', 'common', 10),
  ('species-ceropegia-woodii', 'Ceropegia woodii', 'ceropegia woodii', 'scientific', 10),
  ('species-ceropegia-woodii', 'String of hearts', 'string of hearts', 'common', 10),
  ('species-ceropegia-woodii', 'Rosary vine', 'rosary vine', 'common', 20),
  ('species-ceropegia-woodii', 'Chain of hearts', 'chain of hearts', 'common', 30),
  ('species-kalanchoe-blossfeldiana', 'Kalanchoe blossfeldiana', 'kalanchoe blossfeldiana', 'scientific', 10),
  ('species-kalanchoe-blossfeldiana', 'Flaming Katy', 'flaming katy', 'common', 10),
  ('species-kalanchoe-blossfeldiana', 'Florist kalanchoe', 'florist kalanchoe', 'common', 20),
  ('species-kalanchoe-blossfeldiana', 'Christmas kalanchoe', 'christmas kalanchoe', 'common', 30),
  ('species-kalanchoe-tomentosa', 'Kalanchoe tomentosa', 'kalanchoe tomentosa', 'scientific', 10),
  ('species-kalanchoe-tomentosa', 'Panda plant', 'panda plant', 'common', 10),
  ('species-kalanchoe-tomentosa', 'Chocolate soldier', 'chocolate soldier', 'common', 20),
  ('species-sedum-morganianum', 'Sedum morganianum', 'sedum morganianum', 'scientific', 10),
  ('species-sedum-morganianum', 'Burro''s tail', 'burros tail', 'common', 10),
  ('species-sedum-morganianum', 'Donkey tail', 'donkey tail', 'common', 20),
  ('species-sedum-morganianum', 'Burros tail', 'burros tail', 'common', 30),
  ('species-portulacaria-afra', 'Portulacaria afra', 'portulacaria afra', 'scientific', 10),
  ('species-portulacaria-afra', 'Elephant bush', 'elephant bush', 'common', 10),
  ('species-portulacaria-afra', 'Dwarf jade', 'dwarf jade', 'common', 20),
  ('species-portulacaria-afra', 'Spekboom', 'spekboom', 'common', 30),
  ('species-curio-herreanus', 'Curio herreanus', 'curio herreanus', 'scientific', 10),
  ('species-curio-herreanus', 'String of tears', 'string of tears', 'common', 10),
  ('species-curio-herreanus', 'Senecio herreianus', 'senecio herreianus', 'synonym', 20),
  ('species-curio-herreanus', 'String of raindrops', 'string of raindrops', 'common', 30),
  ('species-crassula-perforata', 'Crassula perforata', 'crassula perforata', 'scientific', 10),
  ('species-crassula-perforata', 'String of buttons', 'string of buttons', 'common', 10),
  ('species-crassula-perforata', 'Necklace vine', 'necklace vine', 'common', 30),
  ('genus-aeonium', 'Aeonium', 'aeonium', 'genus', 10),
  ('genus-aeonium', 'Tree houseleek', 'tree houseleek', 'common', 30),
  ('genus-lithops', 'Lithops', 'lithops', 'genus', 10),
  ('genus-lithops', 'Living stones', 'living stones', 'common', 20),
  ('genus-lithops', 'Pebble plant', 'pebble plant', 'common', 30),
  ('genus-gasteria', 'Gasteria', 'gasteria', 'genus', 10),
  ('genus-gasteria', 'Ox tongue', 'ox tongue', 'common', 30),
  ('species-asplenium-nidus', 'Asplenium nidus', 'asplenium nidus', 'scientific', 10),
  ('species-asplenium-nidus', 'Bird''s nest fern', 'birds nest fern', 'common', 10),
  ('species-asplenium-nidus', 'Birds nest fern', 'birds nest fern', 'common', 30),
  ('genus-adiantum', 'Maidenhair fern', 'maidenhair fern', 'genus', 10),
  ('genus-adiantum', 'Adiantum', 'adiantum', 'genus', 10),
  ('genus-adiantum', 'Maidenhair fern', 'maidenhair fern', 'common', 10),
  ('genus-pteris', 'Brake fern', 'brake fern', 'genus', 10),
  ('genus-pteris', 'Pteris', 'pteris', 'genus', 10),
  ('genus-pteris', 'Table fern', 'table fern', 'common', 30),
  ('genus-platycerium', 'Staghorn fern', 'staghorn fern', 'genus', 10),
  ('genus-platycerium', 'Platycerium', 'platycerium', 'genus', 10),
  ('genus-platycerium', 'Elkhorn fern', 'elkhorn fern', 'common', 30),
  ('genus-selaginella', 'Selaginella', 'selaginella', 'genus', 10),
  ('genus-selaginella', 'Spike moss', 'spike moss', 'common', 20),
  ('genus-selaginella', 'Club moss', 'club moss', 'common', 30),
  ('species-soleirolia-soleirolii', 'Soleirolia soleirolii', 'soleirolia soleirolii', 'scientific', 10),
  ('species-soleirolia-soleirolii', 'Baby''s tears', 'babys tears', 'common', 10),
  ('species-soleirolia-soleirolii', 'Baby tears plant', 'baby tears plant', 'common', 20),
  ('species-soleirolia-soleirolii', 'Mind-your-own-business', 'mind your own business', 'common', 30),
  ('species-howea-forsteriana', 'Howea forsteriana', 'howea forsteriana', 'scientific', 10),
  ('species-howea-forsteriana', 'Kentia palm', 'kentia palm', 'common', 10),
  ('species-howea-forsteriana', 'Thatch palm', 'thatch palm', 'common', 30),
  ('species-rhapis-excelsa', 'Rhapis excelsa', 'rhapis excelsa', 'scientific', 10),
  ('species-rhapis-excelsa', 'Lady palm', 'lady palm', 'common', 10),
  ('species-rhapis-excelsa', 'Broadleaf lady palm', 'broadleaf lady palm', 'common', 20),
  ('species-caryota-mitis', 'Caryota mitis', 'caryota mitis', 'scientific', 10),
  ('species-caryota-mitis', 'Fishtail palm', 'fishtail palm', 'common', 10),
  ('species-caryota-mitis', 'Clustering fishtail palm', 'clustering fishtail palm', 'common', 30),
  ('species-dracaena-fragrans', 'Dracaena fragrans', 'dracaena fragrans', 'scientific', 10),
  ('species-dracaena-fragrans', 'Corn plant', 'corn plant', 'common', 10),
  ('species-dracaena-fragrans', 'Cornstalk dracaena', 'cornstalk dracaena', 'common', 20),
  ('species-dracaena-fragrans', 'Mass cane', 'mass cane', 'common', 20),
  ('species-dracaena-fragrans', 'Cane plant', 'cane plant', 'common', 30),
  ('species-dracaena-fragrans', 'Happy plant', 'happy plant', 'common', 30),
  ('species-dracaena-fragrans', 'Dracaena massangeana', 'dracaena massangeana', 'synonym', 30),
  ('species-dracaena-fragrans', 'Dracaena fragrans ''Massangeana''', 'dracaena fragrans massangeana', 'synonym', 30),
  ('species-dracaena-marginata', 'Dracaena marginata', 'dracaena marginata', 'scientific', 10),
  ('species-dracaena-marginata', 'Dragon tree', 'dragon tree', 'common', 10),
  ('species-dracaena-marginata', 'Madagascar dragon tree', 'madagascar dragon tree', 'common', 20),
  ('species-dracaena-marginata', 'Dracaena reflexa var. angustifolia', 'dracaena reflexa var angustifolia', 'synonym', 30),
  ('species-dracaena-reflexa', 'Dracaena reflexa', 'dracaena reflexa', 'scientific', 10),
  ('species-dracaena-reflexa', 'Song of India', 'song of india', 'common', 10),
  ('species-dracaena-reflexa', 'Pleomele', 'pleomele', 'common', 30),
  ('species-dracaena-reflexa', 'Song of Jamaica', 'song of jamaica', 'common', 30),
  ('species-cordyline-fruticosa', 'Cordyline fruticosa', 'cordyline fruticosa', 'scientific', 10),
  ('species-cordyline-fruticosa', 'Ti plant', 'ti plant', 'common', 10),
  ('species-cordyline-fruticosa', 'Hawaiian ti plant', 'hawaiian ti plant', 'common', 20),
  ('species-cordyline-fruticosa', 'Good luck plant', 'good luck plant', 'common', 30),
  ('genus-aeschynanthus', 'Lipstick plant', 'lipstick plant', 'genus', 10),
  ('genus-aeschynanthus', 'Aeschynanthus', 'aeschynanthus', 'genus', 10),
  ('genus-aeschynanthus', 'Lipstick vine', 'lipstick vine', 'common', 20),
  ('genus-nematanthus', 'Goldfish plant', 'goldfish plant', 'genus', 10),
  ('genus-nematanthus', 'Nematanthus', 'nematanthus', 'genus', 10),
  ('genus-nematanthus', 'Guppy plant', 'guppy plant', 'common', 30),
  ('genus-columnea', 'Columnea', 'columnea', 'genus', 10),
  ('genus-columnea', 'Flying goldfish plant', 'flying goldfish plant', 'common', 30),
  ('species-oxalis-triangularis', 'Oxalis triangularis', 'oxalis triangularis', 'scientific', 10),
  ('species-oxalis-triangularis', 'Purple shamrock', 'purple shamrock', 'common', 10),
  ('species-oxalis-triangularis', 'False shamrock', 'false shamrock', 'common', 20),
  ('species-oxalis-triangularis', 'Love plant', 'love plant', 'common', 30),
  ('species-cyclamen-persicum', 'Cyclamen persicum', 'cyclamen persicum', 'scientific', 10),
  ('species-cyclamen-persicum', 'Florist''s cyclamen', 'florists cyclamen', 'common', 10),
  ('species-cyclamen-persicum', 'Persian cyclamen', 'persian cyclamen', 'common', 20),
  ('species-cyclamen-persicum', 'Cyclamen', 'cyclamen', 'common', 30),
  ('species-begonia-maculata', 'Begonia maculata', 'begonia maculata', 'scientific', 10),
  ('species-begonia-maculata', 'Polka dot begonia', 'polka dot begonia', 'common', 10),
  ('species-begonia-maculata', 'Begonia maculata Wightii', 'begonia maculata wightii', 'common', 30),
  ('species-begonia-maculata', 'Angel wing begonia', 'angel wing begonia', 'common', 80),
  ('species-dionaea-muscipula', 'Dionaea muscipula', 'dionaea muscipula', 'scientific', 10),
  ('species-dionaea-muscipula', 'Venus flytrap', 'venus flytrap', 'common', 10),
  ('species-dionaea-muscipula', 'Venus fly trap', 'venus fly trap', 'common', 20),
  ('genus-dendrobium', 'Dendrobium orchid', 'dendrobium orchid', 'genus', 10),
  ('genus-dendrobium', 'Dendrobium', 'dendrobium', 'genus', 10),
  ('genus-dendrobium', 'Dendrobium orchid', 'dendrobium orchid', 'common', 20),
  ('genus-oncidium', 'Oncidium orchid', 'oncidium orchid', 'genus', 10),
  ('genus-oncidium', 'Oncidium', 'oncidium', 'genus', 10),
  ('genus-oncidium', 'Oncidium orchid', 'oncidium orchid', 'common', 20),
  ('genus-oncidium', 'Dancing lady orchid', 'dancing lady orchid', 'common', 30),
  ('genus-cattleya', 'Cattleya orchid', 'cattleya orchid', 'genus', 10),
  ('genus-cattleya', 'Cattleya', 'cattleya', 'genus', 10),
  ('genus-cattleya', 'Cattleya orchid', 'cattleya orchid', 'common', 20),
  ('genus-cattleya', 'Corsage orchid', 'corsage orchid', 'common', 30),
  ('genus-paphiopedilum', 'Paphiopedilum orchid', 'paphiopedilum orchid', 'genus', 10),
  ('genus-paphiopedilum', 'Paphiopedilum', 'paphiopedilum', 'genus', 10),
  ('genus-paphiopedilum', 'Paphiopedilum orchid', 'paphiopedilum orchid', 'common', 20),
  ('genus-paphiopedilum', 'Lady slipper orchid', 'lady slipper orchid', 'common', 30),
  ('genus-cymbidium', 'Cymbidium orchid', 'cymbidium orchid', 'genus', 10),
  ('genus-cymbidium', 'Cymbidium', 'cymbidium', 'genus', 10),
  ('genus-cymbidium', 'Cymbidium orchid', 'cymbidium orchid', 'common', 20),
  ('genus-cymbidium', 'Boat orchid', 'boat orchid', 'common', 30),
  ('species-pachira-aquatica', 'Pachira aquatica', 'pachira aquatica', 'scientific', 10),
  ('species-pachira-aquatica', 'Money tree', 'money tree', 'common', 10),
  ('species-pachira-aquatica', 'Guiana chestnut', 'guiana chestnut', 'common', 30),
  ('species-pachira-aquatica', 'Malabar chestnut', 'malabar chestnut', 'common', 30),
  ('species-pachira-aquatica', 'Money plant', 'money plant', 'common', 90),
  ('species-dracaena-sanderiana', 'Dracaena sanderiana', 'dracaena sanderiana', 'scientific', 10),
  ('species-dracaena-sanderiana', 'Lucky bamboo', 'lucky bamboo', 'common', 10),
  ('species-dracaena-sanderiana', 'Ribbon dracaena', 'ribbon dracaena', 'common', 30),
  ('species-dracaena-sanderiana', 'Bamboo plant', 'bamboo plant', 'common', 90),
  ('species-araucaria-heterophylla', 'Araucaria heterophylla', 'araucaria heterophylla', 'scientific', 10),
  ('species-araucaria-heterophylla', 'Norfolk Island pine', 'norfolk island pine', 'common', 10),
  ('species-araucaria-heterophylla', 'Norfolk pine', 'norfolk pine', 'common', 20),
  ('species-araucaria-heterophylla', 'Living Christmas tree', 'living christmas tree', 'common', 30),
  ('species-stromanthe-thalia', 'Stromanthe thalia', 'stromanthe thalia', 'scientific', 10),
  ('species-stromanthe-thalia', 'Triostar stromanthe', 'triostar stromanthe', 'common', 10),
  ('species-stromanthe-thalia', 'Stromanthe sanguinea', 'stromanthe sanguinea', 'synonym', 20),
  ('species-stromanthe-thalia', 'Stromanthe Triostar', 'stromanthe triostar', 'common', 20),
  ('species-stromanthe-thalia', 'Tricolor stromanthe', 'tricolor stromanthe', 'common', 30),
  ('species-stromanthe-thalia', 'Prayer plant', 'prayer plant', 'common', 80),
  ('genus-ctenanthe', 'Ctenanthe', 'ctenanthe', 'genus', 10),
  ('genus-ctenanthe', 'Never never plant', 'never never plant', 'common', 20),
  ('genus-ctenanthe', 'Prayer plant', 'prayer plant', 'common', 80),
  ('species-polyscias-fruticosa', 'Polyscias fruticosa', 'polyscias fruticosa', 'scientific', 10),
  ('species-polyscias-fruticosa', 'Ming aralia', 'ming aralia', 'common', 10),
  ('species-polyscias-fruticosa', 'Aralia fruticosa', 'aralia fruticosa', 'synonym', 30),
  ('species-plerandra-elegantissima', 'Plerandra elegantissima', 'plerandra elegantissima', 'scientific', 10),
  ('species-plerandra-elegantissima', 'False aralia', 'false aralia', 'common', 10),
  ('species-plerandra-elegantissima', 'Schefflera elegantissima', 'schefflera elegantissima', 'synonym', 20),
  ('species-plerandra-elegantissima', 'Dizygotheca elegantissima', 'dizygotheca elegantissima', 'synonym', 30),
  ('species-plerandra-elegantissima', 'Threadleaf aralia', 'threadleaf aralia', 'common', 30),
  ('genus-nepenthes', 'Tropical pitcher plant', 'tropical pitcher plant', 'genus', 10),
  ('genus-nepenthes', 'Nepenthes', 'nepenthes', 'genus', 10),
  ('genus-nepenthes', 'Monkey cup', 'monkey cup', 'common', 30),
  ('genus-philodendron', 'Philodendron', 'philodendron', 'genus', 10),
  ('genus-dracaena', 'Dracaena', 'dracaena', 'genus', 10),
  ('genus-peperomia', 'Peperomia', 'peperomia', 'genus', 10),
  ('genus-ficus', 'Ficus', 'ficus', 'genus', 10),
  ('genus-hoya', 'Hoya', 'hoya', 'genus', 10),
  ('care-group-succulent-like', 'Succulent', 'succulent', 'group', 10),
  ('care-group-succulent-like', 'Succulent-like', 'succulent like', 'group', 20),
  ('care-group-cactus', 'Cactus', 'cactus', 'group', 10),
  ('care-group-moderate-tropical', 'Tropical houseplant', 'tropical houseplant', 'group', 10),
  ('care-group-moisture-loving-tropical', 'Moisture-loving tropical', 'moisture loving tropical', 'group', 10),
  ('care-group-fern', 'Fern', 'fern', 'group', 10),
  ('care-group-orchid-bark', 'Orchid in bark', 'orchid in bark', 'group', 10),
  ('care-group-palm', 'Palm', 'palm', 'group', 10),
  ('fallback-unknown-conservative', 'Unknown houseplant', 'unknown houseplant', 'group', 10)
)
insert into public.care_profile_aliases (
  care_profile_id,
  alias,
  normalized_alias,
  alias_type,
  priority
)
select
  care_profiles.id,
  alias_seed.alias,
  alias_seed.normalized_alias,
  alias_seed.alias_type,
  alias_seed.priority
from alias_seed
join public.care_profiles
  on care_profiles.profile_key = alias_seed.profile_key
on conflict (care_profile_id, normalized_alias, alias_type) do update
set
  alias = excluded.alias,
  priority = excluded.priority;
